.changeset/selfish-cheetahs-repair.md
packages/workflow-diagram/src/nodes/TriggerWorkflowNode.tsx

Fix word-wrap on nodes

---

.changeset/big-pets-do.md
packages/workflow-diagram/src/nodes/JobNode.tsx

Align job node titles

---

packages/cli/README.md

Release PR for CLI 0.0.21 (plus dependencies)

CLI release 0.0.21

---

.circleci/config.yml
package.json

Whoops - integration tests were running the wrong test suite!
This PR fixes that...

integration-tests: run correct test suite

---

.changeset/witty-rules-admire.md
packages/cli/CHANGELOG.md
packages/cli/package.json

CLI release v0.0.30
* Fix adaptor version print out again)

Release CLI 0.0.30

---

.changeset/chatty-ravens-switch.md
.changeset/eighty-frogs-protect.md
.changeset/fifty-moles-search.md
.changeset/flat-donkeys-sip.md
.changeset/long-dingos-beam.md
.changeset/lucky-toys-care.md
.changeset/metal-gorillas-clap.md
.changeset/purple-starfishes-fail.md
.changeset/rich-badgers-fold.md
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/compiler/CHANGELOG.md
packages/compiler/package.json
packages/runtime-manager/CHANGELOG.md
packages/runtime-manager/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
pnpm-lock.yaml

Plus additional dependencies.
Features:
* Workflow support
* Fix to metadata cache
Versions have been bumped, to release just `install`, `build` and `publish` please!

CLI Release 0.0.37

---

.changeset/great-bugs-move.md
integration-tests/cli/test/execute-workflow.test.ts
packages/cli/README.md
packages/cli/src/options.ts
packages/cli/test/commands.test.ts
packages/cli/test/execute/options.test.ts
packages/cli/test/options/ensure/strict.test.ts

I've had enough of strict mode and the confusion it brings! 
It's also fundamentally wrong, see #233.
While we work out what to do, this PR simply runs in non-strict mode by default, which makes everyone's life a bit easier.

Non-strict mode by default

---

.changeset/young-dingos-decide.md
packages/cli/src/deploy/command.ts
packages/cli/src/deploy/handler.ts
packages/cli/src/options.ts
packages/deploy/src/client.ts
packages/deploy/src/index.ts

Adds a describe flag for the deploy command so we can sync remote project.yaml to current directory
Fixes #278

Initial pass add adding describe option to deploy

---

.changeset/five-fireants-flow.md
packages/deploy/src/stateTransform.ts
packages/deploy/src/types.ts
packages/deploy/test/fixtures.ts
packages/deploy/test/stateTransform.test.ts

Added description and cron_expression to `cli deploy`

Tidy up deploy, work with new lightning APIs

---

packages/cli/src/cli.ts
packages/cli/src/commands.ts
packages/cli/src/deploy/handler.ts
packages/cli/src/pull/command.ts
packages/cli/src/pull/handler.ts
packages/deploy/src/client.ts
packages/deploy/src/index.ts

- Adds a pull command to the cli
- Pull command should pull state json to the statePath as well as the project yaml to the specPath
Fixes #278

Pull command

---

.changeset/fluffy-dryers-cheer.md
packages/runtime/package.json
packages/runtime/src/util/log-error.ts
packages/runtime/test/execute/plan.test.ts
pnpm-lock.yaml

A issue crept up where a dangling unidentified variable was getting referenced in the error reporter causing a blow up.
It's been fixed, and I've improved the typing and tests.
This should really have been picked up by the build failing for type errors.
Fixes #317

Fix error reporting issue

---

packages/runtime-manager/package.json

Need to merge this after fixing publish

Make runtime manager private again

---

.changeset/ninety-moose-build.md
.circleci/config.yml

Breaking up our circle build into more jobs, which allows concurrency and better restarting on fail

Better circle build

---

packages/ws-worker/src/util/convert-attempt.ts
packages/ws-worker/test/util/convert-attempt.test.ts

runtime: map lightning edge condition strings to valid expressions

---

.github/workflows/publish.yaml
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json

test of publish command
Determined to fix tag pushing - this shouldn't be so hard!

publish: test

---

.github/pull_request_template.md
.github/workflows/publish.yaml
README.md

Update docs to handle tags on releases

release docs

---

.changeset/nice-poets-attack.md
.changeset/warm-elephants-flow.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
integration-tests/worker/test/integration.test.ts
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/package.json
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/runtime/src/execute/expression.ts
packages/runtime/test/execute/expression.test.ts
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/types.d.ts
packages/ws-worker/src/util/convert-attempt.ts
packages/ws-worker/test/integration.test.ts
packages/ws-worker/test/mock/data.ts
packages/ws-worker/test/util/convert-attempt.test.ts

* Fix credentials
* Ensure state is serialised properly in the runtime

Release: Worker 0.2.2

---

.changeset/warm-rules-draw.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/api/reasons.ts
packages/ws-worker/test/reasons.test.ts

I thought this would be difficult, but then I thought some more and I thought it would be easy.
Closes #476
Versions are bumped and this is ready to merge.

Better leaf calculation

---

.changeset/five-mirrors-smile.md
.changeset/old-mails-wash.md
.changeset/selfish-spoons-sort.md
integration-tests/worker/test/exit-reasons.test.ts
packages/engine-multi/src/api/autoinstall.ts
packages/engine-multi/src/api/execute.ts
packages/engine-multi/src/api/lifecycle.ts
packages/engine-multi/src/errors.ts
packages/engine-multi/src/events.ts
packages/engine-multi/src/worker/events.ts
packages/engine-multi/test/api/autoinstall.test.ts
packages/runtime/src/execute/job.ts
packages/runtime/test/execute/job.test.ts
packages/ws-worker/src/api/execute.ts
packages/ws-worker/src/server.ts
packages/ws-worker/test/api/execute.test.ts
packages/ws-worker/test/reasons.test.ts
pnpm-lock.yaml

Our error handling for autoinstall is pretty bad - so I've made it better and added tests.
I hope this will help us catch errors in production.
No issue.

Autoinstall better errors

---

.changeset/tidy-trains-care.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/lightning-mock/src/api-dev.ts
packages/lightning-mock/src/api-sockets.ts
packages/lightning-mock/src/events.ts
packages/lightning-mock/src/server.ts
packages/lightning-mock/src/types.ts
packages/lightning-mock/test/channels/attempt.test.ts
packages/lightning-mock/test/channels/claim.test.ts
packages/lightning-mock/test/data.ts
packages/lightning-mock/test/events/attempt-complete.test.ts
packages/lightning-mock/test/events/attempt-start.test.ts
packages/lightning-mock/test/events/log.test.ts
packages/lightning-mock/test/events/run-complete.test.ts
packages/lightning-mock/test/events/run-start.test.ts
packages/lightning-mock/test/server.test.ts
packages/lightning-mock/test/util.ts
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/api/claim.ts
packages/ws-worker/src/api/execute.ts
packages/ws-worker/src/channels/attempt.ts
packages/ws-worker/src/events.ts
packages/ws-worker/src/index.ts
packages/ws-worker/src/server.ts
packages/ws-worker/src/types.d.ts
pnpm-lock.yaml

This PR:
* Adds validation to mock lightning endpoints
* Tests validation
* Reorganisses the mock a bit
* Closes #492
* Adjusts and corrects some typings in the worker

Harden lightning mocks

---

packages/cli/README.md

Fixed a typo on workflow example

update `cli` readme

---

Dockerfile
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json

Add git to worker image

---

.changeset/green-coins-jam.md
.changeset/lucky-windows-approve.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/package.json
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/runtime/src/execute/job.ts
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/util/convert-attempt.ts
pnpm-lock.yaml

This handles the initial edge condition from a webhook trigger and logs edge evaluations to the attempt
Fixes #551

Handle initial edge condition and log edge evaluations

---

integration-tests/worker/test/autoinstall.test.ts

Trying to break autoinstall...

Autoinstall tests

---

packages/engine-multi/src/worker/pool.ts
packages/engine-multi/test/api/call-worker.test.ts
packages/engine-multi/test/worker/pool.test.ts

Caught an issue in the pool timing out deferred workers.

Fix flaky test

---

packages/cli/package.json

Try and publish `deploy` without publishig `cli`

demote cli

---

.changeset/heavy-lobsters-try.md
packages/cli/CHANGELOG.md
packages/cli/src/docs/handler.ts
packages/cli/src/execute/command.ts
packages/cli/src/util/load-plan.ts
packages/cli/test/commands.test.ts

Some simple CLI changes in response to training session with Lwala
* Debug logging on workflow loading
* Cleaner and prettier docs output
* Small fix to example help

Training feedback

---

.changeset/silly-tomatoes-move.md
integration-tests/cli/test/metadata.test.ts
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/cli/src/metadata/handler.ts
packages/cli/test/metadata/should-autoinstall.test.ts

Release branch for https://github.com/OpenFn/kit/pull/670

CLI: autoinstall for metadata

---

.changeset/silver-impalas-care.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/package.json
packages/lexicon/CHANGELOG.md
packages/lexicon/lightning.d.ts
packages/lexicon/package.json
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/util/convert-lightning-plan.ts
packages/ws-worker/test/channels/run.test.ts
packages/ws-worker/test/util/convert-lightning-plan.test.ts
pnpm-lock.yaml

- Updates  the `runTimeoutMs` key to `run_timeout_ms`
- Adds a future option: `run_memory_limit`
Fixes #677

update lightning plan options to use snake_case

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/deploy/CHANGELOG.md
packages/deploy/package.json
packages/deploy/src/validator.ts
packages/deploy/test/validator.test.ts

Release and final  QA PR for  https://github.com/OpenFn/kit/pull/675
Closes #667

Release:  cli-deploy: allow steps in workflows to have non-unique names

---

.changeset/neat-rice-thank.md
integration-tests/worker/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/cli/src/apollo/cat-facts.example.json
packages/cli/src/apollo/command.ts
packages/cli/src/apollo/handler.ts
packages/cli/src/apollo/util.ts
packages/cli/src/cli.ts
packages/cli/src/commands.ts
packages/cli/src/options.ts
packages/cli/test/apollo/options.test.ts
packages/cli/test/apollo/util.test.ts
packages/deploy/src/index.ts
packages/deploy/src/validator.ts
packages/deploy/test/validator.test.ts
packages/lightning-mock/src/api-dev.ts
pnpm-lock.yaml

release apollo

---

packages/cli/src/docs/handler.ts
packages/cli/src/metadata/handler.ts
packages/cli/src/pull/command.ts
packages/cli/src/pull/handler.ts
packages/cli/src/test/handler.ts
packages/cli/src/util/cache.ts
packages/cli/src/util/load-plan.ts
packages/compiler/src/transforms/lazy-state.ts
packages/describe-package/src/fs/fake-fs.ts
packages/logger/src/index.ts
packages/logger/src/util/timestamp.ts
packages/ws-worker/src/start.ts

This PR runs prettier (2.8.8) on all source files.

Run prettier

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/cli/src/execute/handler.ts
packages/cli/src/util/validate-plan.ts
packages/cli/test/util/validate-plan.test.ts
packages/runtime/test/runtime.test.ts

Release: workflow validation

---

packages/compiler/test/transforms/lazy-state.test.ts

Add a test with logical not and lazy state. This proves it works.
Also runs the formatter on the test file.
Closes #708

compiler: add test for lazy state with logical not

---

.changeset/afraid-oranges-compete.md
.changeset/blue-parrots-thank.md
.changeset/curvy-camels-eat.md
.changeset/selfish-items-applaud.md
.changeset/swift-dots-try.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/package.json
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json

versions: worker@1.20 cli@1.4.0

---

.changeset/neat-games-move.md
packages/lightning-mock/package.json
packages/ws-worker/package.json
pnpm-lock.yaml

Updates a vulnerable version of `jose`.
Fixes #
N/A
N/A
I am not sure what constitutes a `release PR` so I have not performed any of the below steps, but happy to do so should it be required.

Update vulnerable version of jose

---

.changeset/little-hats-doubt.md
packages/compiler/src/compile.ts
pnpm-lock.yaml

compiler: don't log compiled source (by deafault)

---

.changeset/big-paws-tap.md
.changeset/chatty-clocks-relax.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
integration-tests/worker/test/runs.test.ts
packages/ws-worker/CHANGELOG.md
packages/ws-worker/README.md
packages/ws-worker/package.json

Collections next

---

.changeset/shaggy-ways-taste.md
.changeset/tough-buttons-vanish.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/channels/run.ts
packages/ws-worker/src/server.ts
packages/ws-worker/src/start.ts
packages/ws-worker/src/util/cli.ts

Worker: 1.13.1

---

integration-tests/execute/CHANGELOG.md
integration-tests/execute/package.json
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/compiler/CHANGELOG.md
packages/compiler/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/package.json
packages/lexicon/CHANGELOG.md
packages/lexicon/lightning.d.ts
packages/lexicon/package.json
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
packages/ws-worker/src/api/claim.ts

worker 1.13.2 pod_name -> worker_name

---

.changeset/cold-waves-talk.md
integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/package.json
packages/engine-multi/src/api/execute.ts
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json

As title, by special request
Fixes #654

publish limits to info, not debug

---

integration-tests/worker/CHANGELOG.md
integration-tests/worker/package.json
packages/engine-multi/CHANGELOG.md
packages/engine-multi/ava.config.cjs
packages/engine-multi/package.json
packages/engine-multi/src/api/lifecycle.ts
packages/engine-multi/src/engine.ts
packages/engine-multi/src/util/create-state.ts
packages/engine-multi/test/api/lifecycle.test.ts
packages/engine-multi/test/memtest.ts
packages/lightning-mock/CHANGELOG.md
packages/lightning-mock/package.json
packages/ws-worker/CHANGELOG.md
packages/ws-worker/package.json
pnpm-lock.yaml

This PR fixes an issue in the engine where state references are not garbage collected, and so memory leaks over time.
This is a probably cause of at least some lost runs.
Fixes #826
After a heck of a lot of investigation I've worked out that the suspect memory leak flagged by @taylordowns2000 is real. I've also worked out that it comes from the engine, and if you cut out child processes and the runtime and just statically return a large object from each run, the leak still occurs
What seems to be happening is:
- for every run we build a context object, which tracks a bunch of data for and about that run
- This is designed to be a temporary object, dropped as soon as the run completes
- When a run completes, we take the final state object returned by the workflow and write it to this …

Engine: encourage better garbage collection

---

.changeset/purple-forks-drum.md
integration-tests/worker/test/exit-reasons.test.ts
integration-tests/worker/test/integration.test.ts
packages/lightning-mock/src/api-sockets.ts
packages/lightning-mock/test/channels/run.test.ts
packages/ws-worker/src/errors.ts

Log whatever error lightning sends back, including objects.
Fixes #948 
Just `JSON.stringify`

log lightning error objects

---

.changeset/stale-drinks-shout.md
packages/ws-worker/src/api/claim.ts

A one or two-sentence description of what this PR does.
Fixes #
A more detailed breakdown of the changes, including motivations (if not provided in the issue).

stop the claim queue

---

packages/project/src/merge/map-uuids.ts
packages/project/test/merge/map-uuids.test.ts

Merge joe suggestions

---

packages/engine-multi/test/integration.test.ts

Fixes a flaky test in the engine, might close #1038
I think we still have some timing issues in CLI and integration tests though

fix flaky tests I think

---

integration-tests/cli/test/project.test.ts
packages/cli/src/checkout/handler.ts
packages/cli/src/merge/handler.ts
packages/cli/src/projects/handler.ts
packages/project/src/Workspace.ts

I know I said we wouldn't bother with integration tests here but I decided to add one
Then remembered why I wasn't keen: to get really good assertions here on UUID preservation is a lot of work. Gonna save that for the test repo - this just serves as a super basic functionality test

Merge: fix pathing and add a basic integration test
