OpenFn/kit

- packages/compiler/src/index.ts
This PR adds an extra export to the compiler package.
Over in Lightning, I have a requirement to pull .d.ts files out of adaptor packages.
In order to do that, I need access to `fetchDTSListing` and  `fetchFile` from `compiler/package-fs`, which isn't currently exposed by the module.
It probably makes sense to release `@openfn/compiler` as a 0.0.2 version as a result of this change. That way, Lightning can explicitly require this version.
> Expose package-fs

- packages/compiler/src/package-fs.ts
- packages/compiler/test/package-fs.spec.ts
For some reason, when we call [https://unpkg.com/@openfn/language-common@1.7.3/?meta](https://unpkg.com/@openfn/language-common@1.7.3/?meta) for metadata, the resulting `files` list includes type definitions from node modules.
I presume this is something "wrong" with the 1.7.3 package of language-common.
In any case, what this means is that when our shiny new Monaco editor looks for the d.ts for an older module, it pulls down a lot of d.ts files which is a) kinda slow and b) could result in incorrect typings.
While we could work around this in the Lightning repo, it seems sensible to me to add a flag to ignore  node_modules paths when running `flattenFiles`. I've defaulted this to `false`, so that it doesn't break anythhing, but maybe we should default that to `true`.
`fetchDTS` is, so …
> Ignore node modules in flatten

- packages/compiler/tsconfig.json
- packages/workflow-diagram/tsconfig.json
- tsconfig.common.json
Really small thing but I wanted to spin it out of the v2 work I'm doing.
As I'm creating more packages I'm duplicating a lot of tsconfigs - I jut wanted to take a breather and abstract out the main compiler rules into the top level and have each package extend it.
Packages are technically free to add their own rules if they want, but we should be looking to apply a consistent set of standards across everything in this repo.
> tsconfig refactor

- .changeset/odd-pugs-hunt.md
- .changeset/stale-dolls-refuse.md
- packages/cli/src/cli.ts
- packages/cli/src/compile/compile.ts
- packages/cli/src/execute/execute.ts
- packages/cli/src/repo/handler.ts
- packages/cli/src/util/ensure-opts.ts
- packages/cli/test/commands.test.ts
- packages/cli/test/execute/parse-adaptors.test.ts
- packages/cli/test/util/ensure-opts.test.ts
- packages/logger/src/mock.ts
- packages/logger/src/sanitize.ts
- packages/logger/test/logger.test.ts
- packages/logger/test/mock.test.ts
- packages/logger/test/sanitize.test.ts
- packages/runtime/src/index.ts
- packages/runtime/src/modules/linker.ts
- packages/runtime/src/modules/module-loader.ts
- packages/runtime/src/modules/repo.ts
- packages/runtime/src/runtime.ts
- packages/runtime/test/modules/linker.test.ts
- packages/workflow-diagram/test/layout.test.ts
Sundry fixes here:
* `openfn repo list` won't throw if the repo is uninitialised
* Better handling of the default repo path
* Fixed docs for logger (removed reference to trace)
* Better debug logging in the linker and repo
* De-emphasise the "exports could not be found" warning as it doesn't matter and looks too scary
* Globals are fine and working as I expect (if a package isn't in the repo then a general `import()` will load the global).
I think tilde in path is fine - works for me (TM) in job path, adaptor path and state path. There are until tests for this in `cli/test/commands/test/ts` (see `run a trivial job from a folder: openfn ~/openfn/jobs/the-question`)
* When a specific adaptor version is passed in, the runtime now actually uses it
Close #67 and #70
> Cli fixes & Improvements

- .changeset/mean-boxes-listen.md
- .changeset/tidy-beds-rush.md
- packages/adaptor-docs/package.json
- packages/workflow-diagram/README.md
- packages/workflow-diagram/package.json
- packages/workflow-diagram/rollup.config.mjs
- pnpm-lock.yaml
- @openfn/workflow-diagram no longer injects it's CSS styles as it's loaded.
- @openfn/adaptor-docs no longer includes esbuild and others as runtime dependencies
Fixes #
> workflow-diagram should have external CSS

- .changeset/forty-boats-poke.md
- .changeset/mean-jobs-sniff.md
- examples/adaptor-docs/src/App.tsx
- examples/adaptor-docs/src/app.tsx
- examples/adaptor-docs/src/index.tsx
- packages/adaptor-docs/src/useDocs.tsx
- packages/describe-package/package.json
- packages/describe-package/src/api.ts
- packages/describe-package/src/describe-project.ts
- packages/describe-package/src/typescript/project.ts
- packages/describe-package/src/typescript/wrapped-symbol.ts
- packages/describe-package/test/describe-project.test.ts
- packages/describe-package/test/describe-types.test.ts
- packages/describe-package/test/fixtures/stroopwafel.d.ts
- packages/describe-package/test/helpers.ts
- pnpm-lock.yaml
This PR ensures that adaptor documentation includes functions exported from language-common.
Basically `describe-package` was failing to describe anything at all for functions exported from another package - ie, the way language-primero exports most of  language-common. This is because the local typescript context only has definitions for the top package (primero) and not its dependencies (common).
This is a quick fix which always loads common alongside whichever adaptor is being described, which should fix most if not all exports for the forseeable future.
Ultimately, the fix for this is to dynamically import whatever is needed. But that has to be a server-side operation, not something that will run in the client. So I'm putting it off for another day.
Note that there is still some chaos …
> Fix exports from common

- .changeset/eight-seahorses-prove.md
- packages/adaptor-docs/src/DocsPanel.tsx
- packages/adaptor-docs/src/index.css
- packages/adaptor-docs/src/render/Function.tsx
Simple PR to nest each line of documentation in a little collapser:
Very simple implementation using HTML `<details>` (thanks @taylordowns2000!). One day we can add something a bit flashier but for now this is a huge improvement.
Closes #82
> Collapsible docs

- examples/adaptor-docs/tsup.config.js
- packages/describe-package/src/api.ts
A simple fix to exclude beta from the documentation exported by `desrcribe-package`.
This is the dumb solution which is fine for now.
What we should REALLY be doing is parsing the index and tracing the actual exports. This would let us properly trace export aliases and present a more accurate picture of what the adaptor exports (not just what code happens to be lying around in the folder).
I've updated the internal documentation to represent what describe package now does:
* Only describe functions marked as @public in the jsdoc
* Ignore the beta.d.ts file
This closes #80
You can test it works by starting up `examples/adaptor-docs` and looking at the dev console. No more duplicate key errors.
> describe-package: Don't describe beta

- .changeset/proud-comics-develop.md
- packages/logger/package.json
- packages/logger/src/logger.ts
- pnpm-lock.yaml
From root, running `pnpm audit --prod` raises a vulnerability in `set-value`, which comes from `prompt-confirm`.
This PR simply replaces the old and busted `prompt-confirm` with the new hotness `@inquirer/confirm`. Bonus: the new inquirer API is _slightly_ nicer.
An audit from this branch should result in no vulnerabilities.
Some vulnerabilities are raised from dev dependencies but I don't intend to address those.
Closes #65
> Fix security vulnerabilities

- packages/cli/src/execute/handler.ts
- packages/cli/src/repo/handler.ts
- packages/cli/test/execute/autoinstall-targets.test.ts
If you do:
`openfn ia -a common=path/to/common`
You'll get an exception because the CLI runs `npm install common=path/to/common`. This is silly. Ok, so it doesn't make sense to ask for an autoinstall if you're going to tell the CLI where to find a module, but nothing should explode.
This PR simply ignores any adaptor arguments with a path.
Fixes #77.
I spent some time this afternoon trying to set up some mocks with `testdouble`  so that I could mockout the install function and test the command a bit better. But I couldn't get it to work :( I'll spend more time on this later but for now it's too much sffort.
> Fix autoinstall with paths

- .changeset/famous-chicken-marry.md
- .changeset/rude-shrimps-beg.md
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands.ts
- packages/cli/src/execute/command.ts
- packages/cli/src/execute/handler.ts
- packages/cli/src/execute/serialize-output.ts
- packages/cli/src/repo/handler.ts
- packages/cli/src/util/ensure-opts.ts
- packages/cli/test/commands.test.ts
- packages/cli/test/compile/compile.test.ts
- packages/cli/test/execute/handle-output.test.ts
- packages/cli/test/execute/serialize-output.test.ts
- packages/cli/test/util/ensure-opts.test.ts
- packages/logger/src/sanitize.ts
- packages/logger/test/sanitize.test.ts
- pnpm-lock.yaml
Three fixes here related to what we write to `output.json`
1) Support circular structures thanks to `fast-safe-stringify` (fixes #106 which started all this)
2) Introduce a "strict mode" for state output, which only prints state.data to the output file
3) Don't serialize `configuration`
The second part in particular is worth some discussion.
By default the CLI will output in strict mode. This means we only print the `data` key of state. Anything else written to the state object will be ignored.
This avoids us serialising junk which is needed at runtime but shouldn't be returned at the end. Like request objects from the HTTP adaptor (which is the trigger for all this).
In non strict mode (`openfn job.js --no-strict-output`) we'll try and print the whole state object (except config, see …
> Tighten up output and support circular structures

- .changeset/real-jokes-fail.md
- packages/cli/src/process/runner.ts
- packages/cli/src/process/spawn.ts
When running in Windows, the CLI just freezes forever.
This is because the packing forked process doesn't receive its startup messages. Basically the start event is sent before the inner process is ready to listen to it. It's a timing thing.
I've just added another event from child to parent which fixes the issue.
> Fix CLI in windows

- packages/runtime-manager/test/worker-pool.test.ts
- packages/runtime/src/runtime.ts
- packages/runtime/test/security.test.ts
I've been adding some unit tests around security concerns - may as well merge them!
Some are around worker threads, others around the runtime sandbox.
There is some duplication here but a little redundancy is no bad thing.
There's also a tiny "fix" for #104 - having understood a bit better what createContext is doing I've removed a comment and made a tiny tweak. So I've targeted this against the release branch but I won't add a changeset.
> Security tests

- .changeset/breezy-baboons-scream.md
- packages/adaptor-docs/package.json
- packages/cli/package.json
- packages/compiler/package.json
- packages/describe-package/CHANGELOG.md
- packages/describe-package/package.json
- packages/describe-package/src/api.ts
- packages/describe-package/src/describe-project.ts
- packages/describe-package/test/describe-project.test.ts
- packages/describe-package/test/fixtures/stroopwafel.d.ts
- packages/runtime-manager/package.json
- packages/runtime/package.json
- pnpm-lock.yaml
Some examples include a caption, which is like a label.
We don't handle that very elegantly - at least, not until now.
It's an awkward cross-package issue but this This fixes https://github.com/OpenFn/Lightning/issues/503
I'll test this against a corresponding fix in Lightning but when we're ready, I suggest we release `describe-package` here then merge down into main.
Update: I've updated workspace dependencies to `workspace:*`, otherwise things get a bit inconsistent if you just try to bump and release a single package.
> describe-package: handle captions in examples better

- .changeset/chilly-rabbits-speak.md
- .changeset/green-snails-jam.md
- examples/dts-inspector/CHANGELOG.md
- examples/dts-inspector/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/compiler/src/transforms/add-imports.ts
- packages/compiler/test/transforms/add-imports.test.ts
- packages/describe-package/CHANGELOG.md
- packages/describe-package/package.json
- packages/runtime-manager/CHANGELOG.md
- packages/runtime-manager/package.json
Turns out that if you have `undefined` in your JS, we'll treat it as a global variable and try to import it from the adaptor.
Whoops.
This PR fixes that and covers a couple of similar cases.
> Fix import undefined

- .changeset/smart-fans-laugh.md
- packages/cli/src/docs/handler.ts
- packages/runtime/src/modules/repo.ts
This PR fixes a silly issue in the `openfn docs` command, where if you don't pass a version number in, the automatic latest version lookup fails.
It also corrects a typing in `runtime`, for which I do not intend to submit a changeset.
So there are no unit tests on this, which is a large part of how this got shipped in a broken state.
Why are there no unit tests? Well, because to test this we shell out to `npm view`, and I don't particularly want to do that in a unit test. I need to either mock the command (which may not have worked anyway in this case because a bad argument was being passed to `getLatestVersion` and the TS is actually a bit wrong); or use an alternative to `npm view` (like calling out to `jsdelivr`) and maybe mock that.
I'm not really a big fan of heavily mocked …
> CLI: Fix docs command

- .changeset/large-hats-help.md
- .changeset/unlucky-rice-move.md
- packages/cli/src/docs/command.ts
- packages/cli/src/docs/handler.ts
- packages/cli/test/commands.test.ts
- packages/describe-package/src/api.ts
So `describe-package` changed how it handles examples in #127 and someone forgot to update the CLI to the new structure. So docs example would output [object Object]. 
This PR fixes this.
I've also sneaked in a fix for #133 because I was right in the zone.
> CLI: more docs fixes

- .changeset/breezy-spies-approve.md
- .changeset/ninety-months-drop.md
- packages/cli/src/commands.ts
- packages/cli/src/execute/command.ts
- packages/cli/src/execute/execute.ts
- packages/cli/src/util/ensure-opts.ts
- packages/cli/test/util/ensure-opts.test.ts
- packages/runtime/src/runtime.ts
- packages/runtime/test/context.test.ts
- packages/runtime/test/runtime.test.ts
- packages/runtime/test/security.test.ts
This PR enables the runtime to timeout after a number of milliseconds.
It's a pretty simple implementation. I've had to touch some error handling stuff - which isn't generally very good. This has prompted me to open #143 as a prelude to further work.
What's important here is that after the timeout the top promises will throw an exception, bringing the process to an end. There's some reasonable logging and a corresponding flag in the CLI to override the default value.
Fixes #68
> Runtime timeouts

- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/compiler/src/util.ts
- packages/compiler/test/transforms/add-imports.test.ts
- packages/compiler/test/util/is-relative-specifier.test.ts
- packages/runtime-manager/CHANGELOG.md
- packages/runtime-manager/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/modules/linker.ts
- pnpm-lock.yaml
This PR:
* Fixes package imports for Windows
* Bumps verison numbers ready for release.
When `import`ing on Windows, it turns out we explicitly have to pass in `file://` as a prefix for local modules.
I don't think this was an issue before so maybe it's the node19 changes (ie node using node module resolution) which have instigated this.
To test this on Windows:
* Check out the pnpm
* `pnpm install`
* `pnpm -r build`
* `pnpm pack:local`
* `pack:local` will return an npm instal path - run it (basically `npm install -g dist/openfn-cli-0.0.26-local.tgz`)
* `openfn version` should report `0.0.16`
* Run a job `openfn job.js -ia http`
> Release: CLI  0.0.26  - Fix windows issues

- packages/describe-package/src/api.ts
When calling `describePackage` on a package without a dependency on `@openfn/language-common`, the function blows up. Which isn't very good, as old adaptors and non-adaptors fail to work.
This PR just relaxes that constraint a bit with some defensive code.
I also updated the fetch so that when looking up common's `d.ts`, it will use the specific version of common, not the latest. I seem to remember thinking about this a while ago and deciding it wasn't worth version-matching - but hey, I've just done it now, so I don't know what I was worried about before.
Closes #160 for now, although `beyonic@0.1.1` will still fail to load in Lightning. At least we can handle the case more gracefully now.
No unit tests because this package makes me sad. I need a week to re-write the whole thing …
> Describe-docs: Don't blow up if there isn't a common dependency

- .changeset/nervous-fireants-check.md
- .changeset/red-dolls-admire.md
- packages/cli/src/util/print-versions.ts
- packages/cli/test/util/print-versions.test.ts
- packages/logger/src/index.ts
When running a job, we print out version details of a few choice modules, including the adaptor.
We deliberately kept this simple to avoid doing lots of heavy module resolution early in the process (and to avoid duplication of critical and complex functionality). 
But we missed something!
When a path is passed for an adaptor, we can't just echo this back to the user, like we do with `-a http@1.0.0`.
So in this PR, we now follow the path and try to load the version from the package.json we find there. If this is a problem, we just report `unknown`.
This will fix version number reporting in Lightning (quite important).
I've also lightly tweaked the presentation of this stuff to be a little nicer.
Fixes #173
> Fix adaptor version paths

- .changeset/red-cats-exercise.md
- packages/cli/README.md
- packages/cli/src/commands.ts
- packages/cli/src/execute/execute.ts
- packages/cli/src/execute/load-state.ts
- packages/cli/src/test/handler.ts
- packages/cli/src/util/ensure-opts.ts
- packages/cli/test/util/ensure-opts.test.ts
This PR stops defaulting the state location to state.json.
If users want to load some state, they must now pass a path explicitly.
This has a few benefits:
* It's safer because we'll never accidentally suck in a state.json which prod credentials in it
* There are few errors about state not being defined if the user intentionally doesn't pass state
This doesn't affect lightning as state is always passed.
Docs and the new CLI tutorial will need to be updated. 
Closes #171
> CLI: No default state

- .changeset/witty-rules-admire.md
- packages/cli/src/util/print-versions.ts
- packages/cli/test/util/print-versions.test.ts
The previous attempt to fix #173, in which adaptor versions are not printed in lightning, failed for two reasons:
1) We calculated the length of the adaptor name wrongly, resulting in messed up formatting
2) If the path happened to have an `@`  in it (ie, `node_modules/@openfn`), the path was mis-calculated and the version was reported as unknown.
Both issues should now be fixed.
Here's my local lightning with this fix in place:
This actually fixes #173. Promise
> Fix version logs again

- examples/dts-inspector/CHANGELOG.md
- examples/dts-inspector/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/describe-package/CHANGELOG.md
- packages/describe-package/package.json
- packages/describe-package/src/describe-project.ts
- packages/describe-package/test/describe-project.test.ts
- packages/describe-package/test/fixtures/stroopwafel.d.ts
- packages/runtime-manager/CHANGELOG.md
- packages/runtime-manager/package.json
To address https://github.com/OpenFn/Lightning/issues/657 - enable adaptor docs to indicate which functions support :sparkles: magic :sparkles: - we need to add a little more information to the package description returned by `describe-package`.
Phew, that's a mouthful.
Basically when `describe-package` generates a json object to describe a function, it includes a `magic: false` flag. Now that we have two published adaptors with magic annotations, we sometimes want to set `magic: true`.
This PR does that an unblocks Lightning#657.
Describe package really needs a couple of days of love on it - but luckily this is a trivial implementation and I think we can rush it in.
I have committed version bumps so we  can release directly from this branch.
> describe-package: recognise magic functions

- .changeset/eight-bees-carry.md
- .changeset/fifty-bears-cheat.md
- .changeset/fluffy-games-march.md
- .changeset/little-shrimps-carry.md
- integration-tests/cli/src/run.ts
- integration-tests/cli/test/execute.test.ts
- packages/cli/src/compile/command.ts
- packages/cli/src/compile/compile.ts
- packages/cli/src/execute/command.ts
- packages/cli/src/options.ts
- packages/cli/test/compile/compile.test.ts
- packages/cli/test/compile/options.test.ts
- packages/cli/test/execute/options.test.ts
- packages/cli/test/options/ensure/ignore-imports.test.ts
- packages/compiler/src/transforms/add-imports.ts
- packages/compiler/src/util.ts
- packages/compiler/test/transform.test.ts
- packages/compiler/test/transforms/add-imports.test.ts
- packages/compiler/test/util/preload-adaptor-exports.test.ts
This PR aims to deal with autoimport issues that have cropped up recently.
There are three strategies here:
* Force the CLI to disable generation of auto imports completely with `--ignore-imports`. This is a nuclear option and will likely cause errors, unless the job code has explicit imports. I don't expect anyone to ever use this.
* Tell the compiler to ignore some imported names with `--ignore-imports=parseInt,i,performance`. If anyone ever has trouble compiling a job properly, this is a valid option to override the auto-import behaviour. This would have fixed Alexa's issue yesterday without needing to modify the job code.
* Fix the lookup for an adaptor's exports, which can be used as an input by the compiler to smartly only add imports to packages they belong to. Turns out this was …
> Fix autoimports

- .changeset/late-vans-divide.md
- packages/logger/src/logger.ts
- packages/logger/test/logger.test.ts
- packages/logger/test/mock.test.ts
Simple feature which logs a timestamp as epoch-ms with Date.now().
Feels like a useful thing to track as a first-class property in the log object, and doesn't hurt anyone.
Timestamps are not included in stdout logs.
Fixes #181
> Include timestamp in json logs

- .changeset/angry-kangaroos-lay.md
- packages/cli/README.md
- packages/cli/src/cli.ts
- packages/cli/src/execute/command.ts
I've added more help text to `yargs.help` and the readme. I'm hoping this will help alleviate the confusion of strict state and #194. In practice there's a lot of help text here so I don't know if it'll be very effective.
I've also fixed the terminal width so that args renders its output a bit more nicely.
Making state non-strict will make the problem go away. But if we want to encourage better consideration of how state is used, we need to keep this pain point. So I'm not sure. Better documentation has to to be key though.
Probably closes #194
> CLI: Better help text

- .changeset/new-experts-sin.md
- integration-tests/cli/test/metadata.test.ts
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cli/src/metadata/handler.ts
This PR ensures that when the CLI metadata command logs stuff out, it sanitises state output to remove potentially sensitive information.
The logger is smart enough to recognise a state object with credentials and scrub the values of `configuration`. But we were passing in `state.configuration` to the logger, which is just an object, so it wasn't cleaned.
I thought about adding some kind of force-sanitising API to the logger but I'm not sure that's the right answer, at least not yet.
Integration test added to keep us honest in the future.
Closes #203
> CLI: Don't log credentials in metadata command

- packages/cli/src/metadata/cache.ts
- packages/cli/src/metadata/handler.ts
- packages/cli/test/metadata/generate-key.test.ts
- packages/cli/test/metadata/sort-keys.test.ts
The CLI's metadata command does not take adaptor info into account when loading from the cache.
So if you pass the same config with a new adaptor, the CLI will wrongly return the cached result.
This PR fixes that and closes #215
It also sorts the keys of objects before caching, so `{ user: 'u', pass: 'p' }` and `{ pass: 'p', user: 'u' }` return the same cache key.
> Better metadata caching

- packages/runtime/test/__repo__/node_modules/cjs_1.0.0/index.cjs
- packages/runtime/test/__repo__/node_modules/cjs_1.0.0/package.json
- packages/runtime/test/__repo__/node_modules/ultimate-answer_1.0.0/index.js
- packages/runtime/test/__repo__/node_modules/ultimate-answer_1.0.0/package.json
- packages/runtime/test/__repo__/node_modules/ultimate-answer_2.0.0/index.js
- packages/runtime/test/__repo__/node_modules/ultimate-answer_2.0.0/package.json
- packages/runtime/test/modules/linker.test.ts
Somehow some of our test fixtures  got deleted. I didn't realise because of a  naughty `.only`.
This restores them to their former glory.
> Restore runtime tests

- .changeset/chatty-readers-run.md
- .changeset/empty-boats-happen.md
- .changeset/fast-pears-return.md
- .changeset/great-bugs-move.md
- .changeset/heavy-carpets-compare.md
- .changeset/proud-schools-cheat.md
- .changeset/silly-rings-study.md
- .changeset/smooth-toes-care.md
- .changeset/strange-teachers-laugh.md
- .changeset/thick-eggs-doubt.md
- .changeset/tiny-cheetahs-tie.md
- .changeset/unlucky-socks-brush.md
- integration-tests/cli/package.json
- integration-tests/cli/test/errors.test.ts
- integration-tests/cli/test/execute-workflow.test.ts
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/logger/CHANGELOG.md
- packages/logger/package.json
- packages/runtime-manager/CHANGELOG.md
- packages/runtime-manager/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- pnpm-lock.yaml
This PR contains version bumps for the CLI 0.0.39 plus dependencies.
Strict mode is now disabled by default, and error handling is much improved.
To release, `install`, `build` and `publish`
> Release CLI 0.0.39

- .changeset/small-toys-judge.md
- packages/cli/src/execute/command.ts
- packages/cli/src/options.ts
- packages/cli/test/compile/compile.test.ts
- packages/cli/test/execute/execute.test.ts
A couple of lightweight docs fixes
* The `strict` option was wrongly listed as `no-strict`
* A workflow example wrongly included an adaptor name
Closes #242
We should probably merge and release quickly, its nice and low risk
> Docs fixes

- .changeset/mighty-timers-agree.md
- integration-tests/cli/test/execute-workflow.test.ts
- integration-tests/cli/test/fixtures/wf-array.json
- packages/cli/test/execute/execute.test.ts
- packages/runtime/src/execute/compile-plan.ts
- packages/runtime/src/execute/expression.ts
- packages/runtime/src/execute/plan.ts
- packages/runtime/src/types.ts
- packages/runtime/test/execute/compile-plan.test.ts
- packages/runtime/test/execute/expression.test.ts
- packages/runtime/test/execute/plan.test.ts
- packages/runtime/test/runtime.test.ts
At the moment, when a job runs in a workflow, we pass the _last_ state into it (merging in credentials and defaults of course).
This PR ensures that we only pass the state from the upstream job into the next one.
Closes #227
```
a
/   \
j     k
/ \
x  y
```
In the workflow above, it's important that:
* `j` and `k` receive  immutable copies of the result of `a`
* `x` and `y` receive immutable copies of the state of `k`
As things stand at the moment it's a bit random. Because we just pass state as a pipeline, it'll be something like `k` will get the result of `j`; `x` will get the result of `k`, and `y` will get the result of `x`.
Some changes introduced in this PR:
* Workflows with branches will now return multiple results
* The `configuration` key is now removed from the result state. …
> Ensure jobs only receive upstream state

- integration-tests/cli/test/fixtures/wf-conditional.json
- packages/cli/CHANGELOG.md
- packages/cli/src/test/handler.ts
- packages/cli/test/commands.test.ts
- packages/cli/test/execute/execute.test.ts
- packages/runtime-manager/CHANGELOG.md
- packages/runtime-manager/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/README.md
- packages/runtime/package.json
- packages/runtime/src/execute/compile-plan.ts
- packages/runtime/src/execute/plan.ts
- packages/runtime/src/types.ts
- packages/runtime/src/util/assemble-state.ts
- packages/runtime/test/execute/compile-plan.test.ts
- packages/runtime/test/execute/plan.test.ts
- packages/runtime/test/runtime.test.ts
- packages/runtime/test/util/assemble-state.test.ts
- pnpm-lock.yaml
This PR introduces a couple of subtle changes to workflows:
Versions have been bumped so please release directly from this branch after QA.
There are also some typing changes to support the work.
Basically this:
```
{
jobs: [{
id: 'job1'
data: { count: 22 },
next: { job2: false }
}, {
id: 'job2'
}]
}
```
Should now be this (and will work):
```
{
jobs: [{
id: 'job1'
state: { data: { count: 22 } },
next: { job2: false }
}, {
id: 'job2'
}]
}
```
> Workflow Tweaks

- .changeset/few-trainers-hang.md
- packages/logger/src/sanitize.ts
- packages/logger/test/logger.test.ts
A simple PR to ensure the logger pretty-prints any objects it logs.
This does not affect json logging, so lightning's logs should be unaffected (lightning's logs should be prettified downstream by the log viewer)
We could add an option for this but I'm not sure I see the point right now.
> Pretty logging

- .circleci/config.yml
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands.ts
- packages/cli/src/compile/command.ts
- packages/cli/src/compile/compile.ts
- packages/cli/src/deploy/command.ts
- packages/cli/src/deploy/handler.ts
- packages/cli/src/docgen/command.ts
- packages/cli/src/docgen/handler.ts
- packages/cli/src/docs/command.ts
- packages/cli/src/execute/command.ts
- packages/cli/src/metadata/command.ts
- packages/cli/src/metadata/handler.ts
- packages/cli/src/options.ts
- packages/cli/src/pull/command.ts
- packages/cli/src/pull/handler.ts
- packages/cli/src/repo/command.ts
- packages/cli/src/repo/handler.ts
- packages/cli/src/test/handler.ts
- packages/cli/src/util/command-builders.ts
- packages/cli/tsconfig.json
- packages/cli/tsconfig.test.json
- packages/deploy/package.json
- packages/logger/src/sanitize.ts
- packages/runtime/package.json
- packages/runtime/src/modules/experimental-vm.ts
- packages/runtime/src/util/log-error.ts
- packages/runtime/tsconfig.test.json
- pnpm-lock.yaml
This PR:
1) Fixes (or ignores) all type issues (excluding deploy and all tests)
2) Adds a type checking step to CI
I am not aiming for perfect typings here, just trying to grow up a bit by failing builds on type fail.
There's some pretty flaky stuff in the yargs typings - there's something in the options that causes some commands to fail the type checker. I don't really get it. It may be to do with duplicating/overriding log options (which is due for refactor really soon anyway).
Closes #323
> Fail on type errors

- .circleci/config.yml
- .github/dependabot.yml
- .github/pull_request_template.md
- .github/workflows/publish.yaml
- .gitignore
- package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- pnpm-lock.yaml
- scripts/slack-publish-message.js
This PR adds a github action which will publish packages on merge to main.
Release branches should be assembled as a PR, have versions bumped and tags pushed, and be manually approved.
Once the release branch is merged, the new action will run to install, build, test (just in case) and publish.
Slack messages will be sent to #engineering and #implementation (with different messages).
This can be merged straight into main, ready for the next actual release.
Closes #324
I've also smuggled a dependabot update in here to make sure that examples is ignored and that it only updates once a week (it is infuriating to make a bunch of updates on Tuesday to wake up and see more on Wednesday)
Just to note that there's already a changeset action created for this, but the flow is:
* Merge changes, …
> Automate publish

- .changeset/wet-swans-greet.md
- .changeset/wicked-kiwis-bake.md
- integration-tests/cli/README.md
- integration-tests/cli/test/execute-job.test.ts
- integration-tests/cli/test/fixtures/log.js
- packages/cli/package.json
- packages/cli/src/execute/command.ts
- packages/cli/src/options.ts
- packages/cli/src/util/command-builders.ts
- packages/cli/src/util/logger.ts
- packages/cli/test/commands.test.ts
- packages/cli/test/options/ensure/sanitize.test.ts
- packages/cli/test/options/execute.test.ts
- packages/logger/src/logger.ts
- packages/logger/src/options.ts
- packages/logger/src/sanitize.ts
- packages/logger/src/util/index.ts
- packages/logger/test/logger.test.ts
- packages/logger/test/sanitize.test.ts
- packages/logger/test/util/is-object.test.ts
- pnpm-lock.yaml
This PR adds options to "sanitise" output in the logger.
Which basically means: if someone tries to log state in a production environment, the logger should automatically remove or obfuscate it.
This PR adds three options: obfuscate, summarize, or remove. By default it will not attempt to sanitize objects (except for state, where we ALWAYS sanitize config), because the CLI is primarily developer tooling.
See the comment below for examples.
Fixes #314 (and I think #211  can be closed out now too)
The logger itself takes a `sanitize` argument with different "policies" for what to do when an object or array is logged.
The CLI accepts this as an input and feeds it through to the logger.
If you try and pass an unknown sanitize value, the CLI will abort in very dramatic circumstances (before …
> Logger: Sensitive logging

- packages/cli/README.md
- packages/cli/src/options.ts
- packages/cli/src/util/ensure-log-opts.ts
- packages/cli/test/options/execute.test.ts
- packages/cli/test/util/ensure-opts.test.ts
This PR changes how log levels are parsed in the CLI's `--log` option, using commas rather than spaces to configure logs for multiple components.
Fixes #190
Until now, yargs has greedily parsed log levels as an array, so if you want to specify multiple log levels, you had to do it at the end of the command.
```
openfn job.js --log compiler=debug runtime=debug
```
This PR changes the yargs parser to treat log options as a string, and we split it by comma
```
openfn job.js --log compiler=debug,runtime=debug
```
This is much cleaner for users.
It's a nice simple change which breaks a satisfying number of tests.
Does this break anything in lightning? I don't think it's passing in multiple log levels right now, so it shouldn't do.
> Log levels can be specified anywhere in the command

- .changeset/long-islands-check.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cli/src/options.ts
- packages/cli/src/pull/command.ts
- packages/cli/src/pull/handler.ts
- packages/cli/state.json
- packages/deploy/CHANGELOG.md
- packages/deploy/package.json
- packages/deploy/src/index.ts
- packages/deploy/src/stateTransform.ts
- packages/deploy/src/types.ts
- packages/deploy/src/validator.ts
- packages/deploy/tsconfig.test.json
- pnpm-lock.yaml
Modifies the pull command to consume a project id rather than using state
Related https://github.com/OpenFn/Lightning/issues/250
I added a projectID option to the pull command and used that rather than depending on the presence of a state file
How to test
- Pull this branch
- build the project using `pnpm build` in the `kit/packages/deploy` and `kit/packages/cli` directories
- provide a statePath, specPath, apiKey and endpoint, either via configuration or by options additionally this takes a positional argument a project id
- run the new build as follows `./dist/index.js pull {some_project_if}` with `some_project_id` being an id of a project in the intance from the endpoint 
- The files at your specPath and your statepath will now be updated with your project'd spec and state, if one or …
> Add support to supplying a project id when pulling

- .changeset/fluffy-pets-fly.md
- .changeset/friendly-readers-pay.md
- .changeset/slow-beans-behave.md
- packages/cli/src/util/ensure-log-opts.ts
- packages/cli/src/util/logger.ts
- packages/cli/test/options/execute.test.ts
- packages/cli/test/util/ensure-opts.test.ts
- packages/logger/src/logger.ts
- packages/logger/test/logger.test.ts
- packages/runtime/src/util/log-error.ts
A few small improvements here:
* The logger will always log errors (even if logging is disabled) #163
* The CLI will not print job logs if errors #277
* If you throw a non Error (ie, `throw "whoopsie"`), the runtime will log it
This doesn't really affect much in practice. In the unlikely event that someone is using log=none, they'll start to see the output they expect.
> Logger: Improvements to error handling

- .changeset/afraid-grapes-impress.md
- packages/runtime/src/execute/compile-plan.ts
- packages/runtime/src/execute/expression.ts
- packages/runtime/src/execute/plan.ts
- packages/runtime/src/util/assemble-state.ts
- packages/runtime/test/execute/compile-plan.test.ts
- packages/runtime/test/runtime.test.ts
- packages/runtime/test/util/assemble-state.test.ts
When running a workflow, if state.data is an array, it gets blatted to an object. See unit tests in runtime.test.ts
Fixes #377
There are two really important little fixes here.
First off, when assembling state for a job, we need to be a bit mindful that state.data might not be an object (it could easily be array).
Secondly, if your workflow edges look like `{ next: "job-1" }`, there's a nasty bug where the runtime would load previous state from the wrong job.
> Runtime: ensure state.data can be an array

- integration-tests/cli/test/errors.test.ts
- packages/logger/src/options.ts
This might be contentious. Closes #257
This PR makes the logger, by default, redirect any `logger.error` or `logger.warn` message s to stdout.
The problem is that when errors are logged from job code, they appear out sequence in the shell because they're written to a different stream. This can result in very confusing log output.
The solution is to make the default log emitter - the thing the logger eventually calls `console.log` on - redirect errors and warnings. This is kinda nice because it doesn't affect the mock logger and none of our unit tests break.
This behaviour can be overridden by passing a different emitter (ie, `console`) object when calling `createLogger`.
An alternative implementation would be to make the CLI pass a different lo emitter, so that by default the logger uses …
> Logger: print errors to stdout

- .github/workflows/publish.yaml
- packages/runtime-manager/CHANGELOG.md
- packages/runtime-manager/package.json
* Fix auto publish
* Bump runtime manager version just to test
I am not sure whether `pnpm changeset publish` gives me the same report summary as `pnpn publish`. It's hard to test and it doesn't matter - I'm just going to manually generate and push tags. It's all the same.
> Fix auto publish

- .changeset/early-olives-camp.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/engine-multi/src/index.ts
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/lightning-mock/src/api-sockets.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/mock/runtime-engine.ts
- packages/ws-worker/test/mock/runtime-engine.test.ts
- pnpm-lock.yaml
- scripts/slack-publish-message.js
Whoops - turns out I was using the wrong attempt name to map log events.
Closes #434 
This PR fixes it, adds a wee fix to the lightning mock, and updates typings.
We did have some unit tests around this but they were also using the wrong name.
> Worker: Fix attempts log

- .github/workflows/publish.yaml
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/workloop.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/util/try-with-backoff.ts
* CLI now takes backoff min/max, in seconds. To call every half second with a max backoff of 30 seconds, do `pnpm start --backoff 0.5/30`
* Slightly reduced the backoff multiplier to slow down the backoff
* Refactored some options
> Worker: Backoff tuning

- .changeset/sour-bees-jam.md
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/src/worker/worker.ts
- packages/engine-multi/test/integration.test.ts
- packages/runtime/test/runtime.test.ts
Right now if you pass initial state into an execution plan, only the data key will actually be passed into the runtime job.
This is a strict mode issue (which is annoying because while the idea of strict mode is sort of sound the current implementation of it is totally bogus).
The fix is simply to disable strict mode in the engine.
Proof of the pudding is the new unit and integration tests.
> Worker: fix initial state handling

- integration-tests/worker/test/integration.test.ts
- packages/runtime/test/execute/expression.test.ts
When the runtime completes, it emits a `run-complete` event with the final state.
This final state may not be serializable (as in with http response objects), which can cause blowups.
This PR just serialises the state a little earlier and makes sure what we broadcast is safe
Closes #464.
TODO: 
* Add a unit test on the serialization specifically
* Why did integration tests not catch this? It's a great test case
* Are there any other event which may exhibit the same problem?
> 464 fix runtime err

- .changeset/warm-elephants-flow.md
- packages/ws-worker/test/integration.test.ts
- packages/ws-worker/test/mock/data.ts
- packages/ws-worker/test/util/convert-attempt.test.ts
This branch fixes credential mapping in the worker. Which is broken.
Closes #465
TODO:
> Worker: fix credential handling

- .changeset/unlucky-tips-crash.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/api/reasons.ts
- packages/ws-worker/test/api/reasons.test.ts
- packages/ws-worker/test/reasons.test.ts
When calculating the exit reason on a failed run, we should only consider leaf nodes. It doesn't matter if a non-leaf node errors if the final leaf node succeeds.
Closes #468
In the case of multiple fails on multiple leaves, right now the first fail will be reported (where "first" is a bit arbitrary). This is something we might want to look at again a bit later.
Note that a crash, kill or exception on ANY node will still report that error as the fail reason. This PR only affects attempts which complete the run.
I will later add more integration tests to  cover these cases - I don't really have the infrastructure in place yet
> Worker: only count leaf nodes when working out fail reasons

- .changeset/empty-pugs-fetch.md
- .changeset/tasty-doors-rush.md
- integration-tests/cli/test/execute-workflow.test.ts
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/errors.ts
- packages/runtime/src/execute/expression.ts
- packages/runtime/src/execute/job.ts
- packages/runtime/test/errors.test.ts
- packages/runtime/test/execute/plan.test.ts
- packages/runtime/test/runtime.test.ts
- packages/runtime/test/security.test.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/test/reasons.test.ts
The runtime, after executing an expression (job), should remove the configuration property from state before returning.
But,  if there was an error during execution, it does not do this!
After the runtime finishes executing it calls out to a function to sanitize the state and ensure that it is safely serialisable. This cleaned state then gets pushed downstream (or back to the user).
But in the event of an error, it'll continue executing the workflow without this cleaning step.
If this is a non-leaf node, the next job will run with a clean state and config and it doesn't really matter. But if it's a leaf node, we would return the state object as it appears at the point of error.
This PR ensures we sanitize state even after error, and pass the sanitised state downstream.
Now, here's a …
> Runtime: clean state after fail

- .changeset/five-mirrors-smile.md
- .changeset/old-mails-wash.md
- packages/runtime/src/execute/job.ts
- packages/runtime/test/execute/job.test.ts
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/test/api/execute.test.ts
- packages/ws-worker/test/reasons.test.ts
- pnpm-lock.yaml
Leave the attempt channel when work is finished.
Silly that I'm not doing this already.
I think this is triggering timeout errors after work is finished.
This is one of several small fixes I'm likely to raise - I'll bundle them up here when done
Also: 
* Fix job duration in logs
> Leave channels

- .changeset/five-seals-divide.md
- packages/engine-multi/src/api/call-worker.ts
- packages/engine-multi/src/engine.ts
- packages/engine-multi/src/types.ts
- packages/engine-multi/test/api/call-worker.test.ts
- packages/engine-multi/test/engine.test.ts
- packages/engine-multi/test/integration.test.ts
The existing purge will run after a workflow is completed if the workerpools workers are all idle.
But there are cases when workflows are active but not yet in the worker - when compiling or autoinstalling, for example.
I am a bit worried that we're purging worker threads on active workflows, and that might sometimes cause the workflows to fail.
I don't know, maybe not, it's all a bit woolly. It should be safe to kill an idle worker while autoinstall is running.
But we have been seeing intermittent timing issues in end to end tests, and I'm not seeing them on this branch. Plus this approach does feel a bit more robust and sensible than the old one.
So, we're going to merge it and see.
> Maybe fix purge?

- .changeset/lovely-dodos-guess.md
- packages/lightning-mock/src/api-dev.ts
- packages/runtime/src/execute/context.ts
- packages/runtime/src/runtime.ts
- packages/runtime/test/runtime.test.ts
- packages/ws-worker/src/mock/runtime-engine.ts
- packages/ws-worker/test/api/execute.test.ts
- packages/ws-worker/test/lightning.test.ts
- packages/ws-worker/test/mock/runtime-engine.test.ts
Closes #486 
The worker at the moment uses a mock runtime engine to test against.
This is quite reasonable because we don't want to be spinning up loads of threads while unit testing worker functions. It's overkill.
Previously the engine mock did include it's own fake little runtime with very limited functionality. But there are two big problems with this:
1) Job code passed into worker functions doesn't look like job code. It looks weird because it's written to run against the mock
2) Events and errors coming out of the runtime are quite complex, and the worker needs to be able to run real and sophisticated workflows to test certain behaviours. It's too hard to simulate this in a mock, so I'm using real code instead.
The mock engine does not autoinstall. It will call the credentials …
> Worker: use real runtime in unit tests

- .changeset/stale-spies-rush.md
- Dockerfile
This PR changes the `CMD` for the ws-worker image so it defaults to starting with node. It's been tested and is working on demo.openfn.org
> Default to starting ws-worker image with node, not pnpm

- .changeset/honest-otters-cry.md
- .changeset/moody-bulldogs-camp.md
- .changeset/two-hounds-listen.md
- integration-tests/worker/src/factories.ts
- integration-tests/worker/src/init.ts
- integration-tests/worker/test/autoinstall.test.ts
- packages/engine-multi/README.md
- packages/engine-multi/src/api.ts
- packages/engine-multi/src/api/autoinstall.ts
- packages/engine-multi/test/api/autoinstall.test.ts
- packages/ws-worker/README.md
- packages/ws-worker/src/start.ts
We are seeing numerous problems in autoinstall in production: see #503
My theory is that if the worker can install two seperate adaptors at once, which is causing interference when installing common dependencies like `lodash`.
This PR enforces autoinstall to use a strict queuing system. Only one adaptor can be installed at a time, and other adaptors must wait.
Also, as a bit of a prelude for this work I've done gone and fixed #454
> Autoinstall issues

- .changeset/fifty-students-pay.md
- .changeset/happy-pianos-cheat.md
- .changeset/ninety-fireants-melt.md
- ava.config.js
- integration-tests/worker/test/attempts.test.ts
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/src/api/lifecycle.ts
- packages/engine-multi/src/events.ts
- packages/engine-multi/src/worker/events.ts
- packages/engine-multi/src/worker/mock-worker.ts
- packages/engine-multi/test/api/lifecycle.test.ts
- packages/engine-multi/test/integration.test.ts
- packages/runtime/ava.config.cjs
- packages/runtime/memtest.ava.config.cjs
- packages/runtime/package.json
- packages/runtime/src/execute/job.ts
- packages/runtime/src/types.ts
- packages/runtime/test/execute/job.test.ts
- packages/runtime/test/memory.test.ts
- packages/runtime/test/repo/get-latest-installed-version.ts
- packages/runtime/test/runtime.test.ts
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/mock/runtime-engine.ts
- packages/ws-worker/test/api/execute.test.ts
- packages/ws-worker/test/lightning.test.ts
- packages/ws-worker/test/mock/runtime-engine.test.ts
This PR will:
* Record memory usage at the end of every job
* Log it to stdout (which the worker will pick up and send to lightning as log)
* Emit it as an event (which the worker can pick up and send directly to lightning)
Closes #28
Note: This does NOT limit memory usage or kill a worker which exceeds a limit - that's a separate piece of work.
CLI output:
We use `process.memoryUsage()` to report memory usage to the user.
This is a **snapshot** of memory at the moment we call the function. Which, right now, as at the end of a **job**.
This is not a particularly reliable number and represents final, not peak, memory allocation. See the discussion below.
We get a few numbers of out of `process.memoryUsage()`, see the discussion at the end of the issue. I am choosing to represent `heapUsed` …
> Runtime: report memory usage

- .changeset/twenty-oranges-push.md
- packages/engine-multi/src/api/call-worker.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/errors.ts
- packages/engine-multi/src/worker/worker-helper.ts
- packages/engine-multi/test/errors.test.ts
Catch async errors to better handle stuff like the postgres syntax error in #509
Fun one this!
Usually when job or adaptor code throws, the exception is caught in, well, a few places actually. It eventually bubbles back out to the worker where it'll be handled.
But! Those wrapping catches only apply to the original callstack. Any async code which uses setTimeout or process.nextTick or something will throw to the process root and cause an exit.
In other words we can't catch this bad boy and bad things happen:
```
fn((s) => return new Promise(() => {
setTimeout(() => { throw \"e\" }, 1) }
))
```
The solution is to use the handy `process.on('uncaughtException',fn)` as a catch-all. This lets us catch any off-piste errors and return a nice error event out to the worker.
It's worth noting that …
> Catch async errors (fixes postgres)

- .changeset/violet-ligers-walk.md
- integration-tests/worker/test/exit-reasons.test.ts
- packages/engine-multi/src/api/call-worker.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/errors.ts
- packages/engine-multi/src/worker/worker-helper.ts
- packages/engine-multi/test/__repo__/node_modules/helper_1.0.0/index.cjs
- packages/engine-multi/test/__repo__/node_modules/helper_1.0.0/package.json
- packages/engine-multi/test/__repo__/package.json
- packages/engine-multi/test/errors.test.ts
So it turns out that some adaptors trigger a process.exit and that causes us all sorts of problems - see #520 for details and a reproduction.
There is a limit to what we can do about this. Inside the worker we can listen for `process.on('exit')`, but we have to run synchronous code in there. We don't actually seem to be able to send a message out of the worker thread.
So instead, outside the thread in the main process, we keep an eye out for workers which throw with a message like `Workerpool Worker terminated Unexpectedly`. Looking at the workerpool source I'm reasonably confident that this is only triggered by process.exit.
So we can detect an early exit and report a vague exit reason. I'm calling it a `kill` (although it's an internal rather than external kill)
Lightning should now get …
> Handle process exit 

- .changeset/angry-islands-tan.md
- packages/ws-worker/src/util/convert-attempt.ts
- packages/ws-worker/test/util/convert-attempt.test.ts
A small PR to make edge conditions a bit more robust
There is no issue for this. I just noticed today that if an upstream job fails to return state, the edge condition will fail to execute.
I've updated the conditions again in https://github.com/OpenFn/Lightning/issues/1268
> worker: better edge conditions

- .changeset/eighty-moons-smile.md
- packages/cli/src/execute/handler.ts
- packages/cli/test/commands.test.ts
- packages/cli/test/execute/execute.test.ts
- packages/engine-multi/test/integration.test.ts
- pnpm-lock.yaml
A small fix for for the CLI which stops an error being thrown if a workflow doesn't return a state object.
Closes #353 
I don't think this affects the worker - I've been testing around and raising some other PRs in that area.
> CLI:  Don't throw if job doesn't return state

- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/util/versions.ts
- packages/ws-worker/test/events/run-start.test.ts
- packages/ws-worker/test/util/versions.test.ts
Don't report compiler and runtime as `workspace:*`
A real fix will take a little longer - I hope  dynamic import will do it.
But this is just a super quick patch to not log junk data.
Versions are bumped - this just needs to be merged and tagged for release.
> Simplify version reporting

- packages/cli/README.md
> Fix typo `CLI README.md`

- .changeset/seven-seas-sneeze.md
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/api/reasons.ts
- packages/ws-worker/src/events/attempt-error.ts
- packages/ws-worker/src/events/atttempt-complete.ts
- packages/ws-worker/src/util/log-final-reason.ts
- packages/ws-worker/test/api/execute.test.ts
- packages/ws-worker/test/events/attempt-complete.test.ts
- packages/ws-worker/test/events/attempt-error.test.ts
- packages/ws-worker/test/lightning.test.ts
This PR will print the exit reason at the bottom of the log
This log isn't generated by the runtime or the engine - it's added as a sort of post-script by the worker itself. We can't do it anywhere else because only the worker knows what the reason is.
But it's such an important point of feedback I think it's important to include it. Even for success states.
This closes #567
> Worker: Log exit reason in attempt log

- .changeset/angry-ladybugs-breathe.md
- .changeset/mighty-beds-shop.md
- .changeset/old-doors-sparkle.md
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/engine.ts
- packages/engine-multi/test/api/execute.test.ts
- packages/engine-multi/test/engine.test.ts
- packages/ws-worker/src/mock/runtime-engine.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/types.d.ts
- packages/ws-worker/src/util/convert-attempt.ts
- packages/ws-worker/test/channels/attempt.test.ts
- packages/ws-worker/test/lightning.test.ts
- packages/ws-worker/test/reasons.test.ts
- packages/ws-worker/test/util/convert-attempt.test.ts
This PR bundles a few things:
* Uses env vars in worker config
* Adds an `attemptTimeout` to the worker and engine. I don't think this is the place to rename it to `runTimeout` for the new terminology, so that will follow
* Adds better logging of config to the worker, so it's clearer what's happening
Targeting the fancy-engine rework (I may merge it in)
Closes #500 #439
Note that #414 is is still outstanding in the runtime and CLI. I want to create `attemptTimeout` and `runTimeout` options there so that it's always clear what you mean by timeout.
> Options improvements

- packages/lexicon/index.d.ts
- packages/lexicon/index.js
- packages/lexicon/lightning.d.ts
- packages/lexicon/lightning.js
- packages/lexicon/package.json
- packages/ws-worker/src/channels/worker-queue.ts
- packages/ws-worker/test/channels/worker-queue.test.ts
_Temporarily targeted at `lexicon` as that's where I branched from._
This PR encodes `api_version` and `worker_version` into the URL to connect to the worker queue.
API version represents the API spec/contract supported by this worker version. That uses a `major.minor` numbering scheme, where `major` is the actual spec version (`v1`), and `minor` is the implementation version (also `v1`).
The worker_version is the npm version of the actual worker.
Although I think `api_version` is the more valuable feature, it is cheap and easy to send both ¯\_(ツ)_/¯
Closes #563
> Send worker versions

- packages/cli/src/commands.ts
- packages/cli/src/util/print-versions.ts
- packages/cli/test/util/print-versions.test.ts
- packages/ws-worker/src/util/versions.ts
- packages/ws-worker/test/util/versions.test.ts
This PR tidies version output in the CLI and Worker
* When running a job in the CLI, you should only see versions for node, the CLI and the adaptor
* If running out of the monorepo, the version will be listed as "monorepo"
* `openfn --version` should still list the versions of the inner components (ie, runtime and engine)
* When running in the Worker, we should only log node, the worker and the adaptor versions
Closes #588
> Tidy version output

- packages/lexicon/lightning.d.ts
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/channels/run.ts
- packages/ws-worker/src/events/step-complete.ts
- packages/ws-worker/src/util/convert-lightning-plan.ts
- packages/ws-worker/test/events/step-complete.test.ts
- packages/ws-worker/test/lightning.test.ts
- packages/ws-worker/test/util/convert-lightning-plan.test.ts
This PR supports the `output_dataclips` option on run options.
Just need to add a few more test cases and we can merge.
Closes #562
> Support zero persistence

- .changeset/twelve-ravens-listen.md
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/api/preload-credentials.ts
- packages/engine-multi/src/errors.ts
- packages/engine-multi/test/api/preload-credentials.test.ts
- packages/engine-multi/test/integration.test.ts
- packages/lightning-mock/src/api-dev.ts
- packages/lightning-mock/src/api-sockets.ts
- packages/lightning-mock/test/channels/run.test.ts
- packages/ws-worker/src/events/run-error.ts
- packages/ws-worker/test/lightning.test.ts
- packages/ws-worker/test/reasons.test.ts
Closes #600 
This is actually a fix down in the engine.
When loading credentials from Lighting, if any credentials fail to load, we  catch and report the error, and throw in the main validation function.
Previously, because of how credentials are loaded in nested promises, this case resulted in an uncaught exception and everything would blow up. It's more stable now - and we should get a nice error message to explain the fail reason!
> Worker: Better error handling for credential errors

- .changeset/grumpy-candles-applaud.md
- .changeset/yellow-peaches-melt.md
- integration-tests/worker/src/init.ts
- integration-tests/worker/test/autoinstall.test.ts
- integration-tests/worker/test/integration.test.ts
- integration-tests/worker/test/runs.test.ts
- packages/lightning-mock/src/api-sockets.ts
- packages/lightning-mock/src/index.ts
- packages/lightning-mock/src/server.ts
- packages/lightning-mock/src/tokens.ts
- packages/lightning-mock/src/util.ts
- packages/lightning-mock/test/tokens.test.ts
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/api/workloop.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/util/worker-token.ts
- packages/ws-worker/test/lightning.test.ts
The PR verifies the run token (JWT) that Lightning sends with each claim.
Verification means checking the signature against the public key and asserting the `iss` (and `id` TODO) claims.
Support has been added to the lightning mock to generate a real JWT token, which is then used in testing.
I don't have very good explicit testing around this - but some tests do now rely on the tokens being set properly. Integration tests now use tokens, and there is a test to ensure the server is destroyed after a token is rejected. So that's not bad.
Closes #399
> Verify run token

- .changeset/angry-plants-call.md
- .changeset/swift-panthers-divide.md
- integration-tests/worker/dummy-repo/node_modules/@openfn/test-adaptor_1.0.0/index.js
- integration-tests/worker/dummy-repo/node_modules/@openfn/test-adaptor_1.0.0/package.json
- integration-tests/worker/dummy-repo/package.json
- integration-tests/worker/src/init.ts
- integration-tests/worker/test/autoinstall.test.ts
- integration-tests/worker/test/benchmark.test.ts
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/src/api/lifecycle.ts
- packages/engine-multi/test/api/lifecycle.test.ts
- packages/logger/src/logger.ts
- packages/logger/src/mock.ts
- packages/logger/test/logger.test.ts
- packages/ws-worker/src/api/destroy.ts
- packages/ws-worker/src/server.ts
- pnpm-lock.yaml
Treat adaptor logs the same as job logs - don't log them to stdout and gcloud.
Closes #602
> Private adaptor logs

- .changeset/calm-books-care.md
- integration-tests/worker/test/runs.test.ts
- packages/engine-multi/src/api/autoinstall.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/worker/thread/run.ts
- packages/engine-multi/test/api/autoinstall.test.ts
- packages/lexicon/core.d.ts
- packages/runtime/src/execute/compile-plan.ts
- packages/runtime/src/execute/expression.ts
- packages/runtime/src/execute/step.ts
- packages/runtime/src/index.ts
- packages/runtime/src/modules/linker.ts
- packages/runtime/src/modules/module-loader.ts
- packages/runtime/src/types.ts
- packages/runtime/test/execute/compile-plan.test.ts
- packages/runtime/test/execute/expression.test.ts
- packages/runtime/test/modules/module-loader.test.ts
- packages/runtime/test/runtime.test.ts
Closes #268
Bit tricky this one! But I think I've got it.
Every step in a workflow gets compiled by the runtime manager (the CLI or the Engine) and is given an import statement `import { fn } from '@openfn/language-common'`.
It's up to the linker, deep inside the runtime, to decide how how resolve this import. Should we look in the repo? Were we given an explicit mapping? What version do we want?
What usually happens is that the runtime manager (the CLI or worker) will pre-parse the workflow and make a bunch of decisions about these imports. In the CLI, for example, the user might add an explicit path to `language-common`. Or if someone asked for `@latest`, the CLI will maybe autoinstall and replace `@latest` with an actual version (I think).
The problem is that one list of …
> Allow a workflow to support multiple adaptor versions

- .changeset/light-dancers-wink.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/deploy/CHANGELOG.md
- packages/deploy/package.json
- packages/deploy/src/validator.ts
- packages/deploy/test/validator.test.ts
This PR fixes an issue where pulling a project without any workflows throws an error.
The fix is:
a) make the validator lenient if a workflow has no workflows
b) default the workflows map to prevent errors downstream
Versions are bumped and this can be merged for release immediately.
> Fix pull without workflows

- packages/cli/README.md
This PR updates the CLI deploy readme to address an issue where deploying a project using CLI deploy in a  local Lightning instance fails on certain systems and Node.js versions if the endpoint uses 'localhost'. To resolve this, users should use the IP address (e.g., 127.0.0.1) as the endpoint.
Fixes #
> Update CLI Deploy Readme

- .changeset/nice-kids-itch.md
- packages/compiler/src/transform.ts
- packages/compiler/src/transforms/add-imports.ts
- packages/compiler/src/transforms/lazy-state.ts
- packages/compiler/test/compile.test.ts
- packages/compiler/test/transforms/lazy-state.test.ts
Add support for a lazy-state operator `$`, which allows state references to be lazily evaluated.
```
get($.data.url)
```
It should be a straight replacement for any `dataValue()` call, or any simple `(state) => state.data.x` reference.
This is a great solution to https://github.com/OpenFn/adaptors/issues/483
Any reference to  JSON-path like expressions like`$.a.b.c` will be compiled into arrow references, like `(state) => state.a.b.c`. This is syntactic sugar to make it easier to safely pass values from state into operations.
From the doc site. This:
```
create(
'Patient__c',
fields(
field('Name', dataValue('form.surname')),
field('Other Names', dataValue('form.firstName')),
field('Age__c', dataValue('form.ageInYears')),
field('Is_Enrolled__c', true),
field('Enrollment_Status__c', 3)
)
); …
```
> Lazy State Operator

- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/compiler/src/transforms/lazy-state.ts
- packages/compiler/test/transforms/lazy-state.test.ts
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
The lazy state operator `$` is causing trouble if you try to use `$` as a variable, a la:
```
parseXML(state.data, $ => {
const inner = $.load(response.text()); // error
});
```
This PR adds a bit of intelligence to the is-this-a-lazy-state-reference heuristic to ignore $ variable declared in the source. See the unit tests for details.
> Fix lazy state

- .changeset/afraid-seals-share.md
- .changeset/five-ligers-suffer.md
- .changeset/nasty-frogs-join.md
- integration-tests/cli/test/execute-workflow.test.ts
- packages/compiler/src/transform.ts
- packages/compiler/src/transforms/add-imports.ts
- packages/compiler/src/transforms/lazy-state.ts
- packages/compiler/test/transform.test.ts
- packages/compiler/test/transforms/lazy-state.test.ts
Support expressions in lazy state references.
What this really means is that instead of just dumbly expanding `$.data.x` to `(state) => state.data.x`, the compiler will hoist the wrapping arrow (the "open function" reference) higher up the AST. This allows a richer range of expressions to use the `$` symbol.
As a result of this work, I am convinced that this lazy state compilation idea scales robustly and adds a lot of value to users.
Docs PR (to be merged post-release): https://github.com/OpenFn/docs/pull/469
Fixes #649 #638
Here are some examples we can handle thanks to this PR:
```
// template literals
get(`hello ${$.data}`)  ->  get(state => `hello ${state.data}`)
get(`hello ${$.firstname} ${$.lastname}`) -> get(state => `hello ${state.firstname} ${state.lastname}`)
// binary …
```
> Lazy state expressions

- packages/compiler/src/transforms/lazy-state.ts
- packages/compiler/test/transforms/lazy-state.test.ts
This PR makes lazy state a bit more strict.
It explicitly ensures that a `$` operator  is being passed as an argument into a function.
If it has a statement or declaration as a parent before the call expression, an error will be thrown (not a great one tbh but there we go).
This is kind of a quick fix, I may relax the constraint if I think #660 is robust enough
> Fix lazy state stuff

- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/engine-multi/src/api/call-worker.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/api/lifecycle.ts
- packages/engine-multi/src/engine.ts
- packages/engine-multi/src/worker/pool.ts
- packages/engine-multi/src/worker/thread/helpers.ts
- packages/engine-multi/test/errors.test.ts
- packages/engine-multi/test/worker/helper.test.ts
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
This PR fixes an issue where the worker doesn't close down pooled child processes after uncaught exceptions, resulting in the worker refusing to work.
Fixes #664 
What's basically happening is:
- The engine is correctly catching uncaught exceptions (and I think process.exits) when they occur
- And it is correctly sending error events out (these errors may be rubbish but I do think they are sending)
- BUT the engine doesn't properly resolve the promise for that run, so the engine still thinks the workflow is executing
- That means the child process pool doesn't allocate new resources for future work, and so chokes up
The engine should eventually be timing out the runs, but by this point lightning thinks they're dead and isn't listening to events. But I think the backlog will very slowly …
> Fix worker death

- .changeset/eleven-colts-march.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/deploy/CHANGELOG.md
- packages/deploy/package.json
- packages/deploy/src/stateTransform.ts
This provides a better error message when the deploy fails because a workflow is found in `state.json` but not `spec.yaml`.
> better error message for state/spec mismatch on deploy

- .changeset/tidy-gorillas-own.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/channels/run.ts
- packages/ws-worker/src/events/run-complete.ts
- packages/ws-worker/src/mock/sockets.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/test/events/run-complete.test.ts
If the run:complete event error happens to throw, the worker will not close out a Run properly, ie will not free up capacity and claim another run.
This is causing the worker to "jam" silently.
I do not know WHY `run:complete` is timing out on us right now (see [these logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-10T00:06:42.140836231Z;query=labels.%22k8s-pod%2Fapp%22%3D%22global-worker%22%0Atimestamp%3D%222024-05-10T00:06:42.140836231Z%22%0AinsertId%3D%22pgvd1lgqsoczh9gr%22?organizationId=189089165982&project=platform-test-267207)). And we'll have to work that out. But at least the worker shouldn't die silently any more.
I've also added a little bit more logging around this stuff. Most of the time it's junk but it may help us diagnose when the worker isn't …
> Worker: ensure workers are released after an error on run:complete

- integration-tests/worker/test/integration.test.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR adds a couple of integration tests to the worker.
These tests ensure that:
a) the default timeout on the worker, set the env var, is respected
b) a timeout can be set on a run and that will overidde the default
One thing that is NOT covered is the env var itself. But I have manually checked that the env var is being passed through correctly, and server startup logs should verify the actual value being used (note that this is an ENGINE option, not a WORKER option)
No release necessary, we can just merge this.
Closes #686
> Worker timeout tests

- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- integration-tests/worker/test/exit-reasons.test.ts
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/engine-multi/src/errors.ts
- packages/engine-multi/test/api/preload-credentials.test.ts
- packages/engine-multi/test/integration.test.ts
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/test/reasons.test.ts
This PR slightly improves the error reporting when fetching a credential
Related to https://github.com/OpenFn/lightning/issues/1842#event-12798283992
There are  just two changes really:
1) If Lightning returns an error message from `fetch:credential`, append that to the exception
2) Only report one error per credential (ie, if the same credential errors on three steps, only report it once)
Lightning needs to return an error string for us to make any use of this.
A more detailed breakdown of the changes, including motivations (if not provided in the issue).
> engine: return slightly better credential errors

- packages/deploy/src/index.ts
- packages/deploy/src/validator.ts
- packages/deploy/test/validator.test.ts
I'm trying to improve the error messaging when validating project.yaml files
So far I've not been able to make much improvement actually. I think the problems are coming out of the native yaml parser and we're not doing a good job of reporting those.
I've also managed to introduce lots of random errors by indenting the yaml at various places. these trigger blowups without any useful context. Not really sure what to do about these yet.
This might be a much bigger deal than I first thought
Maybe closes OpenFn/lightning#2140
Implementation notes:
* I've refactored the validation tests
* I've refactored "duplicate key" to "duplicate id", which is more user friendly
* I'm ensuring a simple string path on an error object (this may wrong, I may have to revert to an array for consistency with the …
> deploy: improve error messages

- integration-tests/cli/test/errors.test.ts
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/execute/plan.ts
- packages/runtime/src/execute/step.ts
- packages/runtime/src/util/validate-plan.ts
- packages/runtime/test/execute/plan.test.ts
- packages/runtime/test/runtime.test.ts
- packages/runtime/test/util/validate-plan.test.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
This PR enables the runtime call each step multiple times.
Each time a step is called, it passes its output to any downstream steps, and so the downstream steps are run multiple times.
It basically treats a repeated step as if it were a unique step in the workflow. So if step `x` is run twice, the runtime basically runs `x-0` and `x-1` as if there were defined on the plan. Note that actually call `x-0` `x`, because otherwise 8 million tests break. And I think it's a bit cleaner?
Closes #698
* Removed a validation step that looks for steps with multiple inputs and throws
* Adjust the core runtime to ensure that a step can have multiple inputs AND outputs
* Update unit tests
These are the rules of this feature:
* Execution is in SERIES and BREADTH FIRST. If start goes to a and b, and a and …
> Engine: support multiple inputs to a step

- ava.config.js
- packages/cli/src/util/load-plan.ts
- packages/cli/test/util/load-plan.test.ts
Allows the user to add file paths to the `state` and `data` in a workflow. 
Fixes #639 
I have added a function that checks if the `state` is a file path. If it is, the function reads the file. Additionally, if the `data` (or any key inside `state`) is a file path, it will read that file and update the key with the file's content.
For example, if we have
`workflow.json`:
```
{
"workflow": {
"steps": [
{
"id": "1",
"adaptor": "common",
"state": "./state.json",
"expression": "./expression.js"
}
]
}
}
```
`state.json`:
```
{
"data":"./data.json"
}
```
`data.json`:
```
{
"x": 1
}
```
It will compile the workflow as:
```
{
"workflow": {
"steps": [
{
"id": "1",
"adaptor": "@openfn/language-common",
"state": {
"data": {
"x": 1
}
},
"expression": "import { fn } from …
```
> CLI: allow file paths for state and data in a workflow

- .changeset/empty-balloons-beam.md
- examples/dts-inspector/CHANGELOG.md
- examples/dts-inspector/package.json
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/describe-package/CHANGELOG.md
- packages/describe-package/package.json
- packages/describe-package/src/api.ts
- packages/describe-package/src/describe-project.ts
- packages/describe-package/test/describe-project.test.ts
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
`describe-package` will read in the d.ts of  a package and give a nicely formatted JSON description.
But it doesn't do a good job of common functions. They're reported as "namespaces" with no actual content. I've always blamed this on the Typescript compiler and I think I still do.
Anyway, I didn't really expect to fix this, but I was taking a look and I reaslised - although TS doesn't give us those definitions out of the box, we've actually already loaded them in. So it's not much work to cross-reference them.
So now it works! If you ask for the functions of http, it'll now include the defs for common. Hurrah!
> describe-package: include common functions

- .changeset/four-wolves-tease.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cli/src/pull/handler.ts
This is a follow up to https://github.com/OpenFn/kit/pull/732
The cli makes 2 API requests when you run `openfn pull {projectID}` . 
This PR adds the provided snapshot ids to the URL for fetching the `project` spec
Fixes #729 
- I'm a little worried that the logic for building the query params has been duplicated. At the same time, I think it's okay to duplicate it because they are 2 different endpoints and they "could" require different logic.
> Add snapshots to the url for fetching project spec

- .changeset/sweet-bats-know.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- integration-tests/worker/test/integration.test.ts
- packages/lexicon/lightning.d.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/events/run-start.ts
- packages/ws-worker/src/events/step-complete.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/util/cli.ts
- packages/ws-worker/src/util/convert-lightning-plan.ts
- packages/ws-worker/src/util/ensure-payload-size.ts
- packages/ws-worker/test/api/execute.test.ts
- packages/ws-worker/test/events/step-complete.test.ts
- packages/ws-worker/test/util/convert-lightning-plan.test.ts
- packages/ws-worker/test/util/ensure-payload-size.test.ts
Closes #739 #571
Log output with limit printed, log redacted and dataclip not sent:
```
RTE Memory limit: 500mb
RTE Timeout: 300s
RTE Payload limit: 10mb
VER Versions:
▸ node.js                    18.12.1
▸ worker                     1.4.1
▸ @openfn/language-common    1.15.1
R/T Executing 4b9cf63e-82c0-46c3-beca-ad84d8d2daab
R/T Starting step New job
R/T [linker] loading module @openfn/language-common
R/T [linker] Loading module @openfn/language-common from /tmp/openfn/worker/repo/node_modules/@openfn/language-common_1.15.1/dist/index.cjs
R/T Resolved adaptor @openfn/language-common to version 1.15.1
R/T Executing expression (1 operations)
R/T Starting operation 1
JOB (Log message redacted: exceeds 10mb memory limit)
R/T Operation 1 complete in 59ms
R/T Expression complete!
R/T Completed …
```
> Worker: limit payload size

- .changeset/swift-dingos-know.md
- packages/cli/src/pull/handler.ts
- packages/deploy/src/index.ts
- packages/deploy/src/pull.ts
- packages/deploy/src/stateTransform.ts
- packages/deploy/src/types.ts
- packages/deploy/src/validator.ts
- packages/deploy/test/fixtures.ts
- packages/deploy/test/util.ts
- packages/deploy/test/validator.test.ts
Support file paths in job body
Fixes #285 
When the `path` is present in the body, we load the file's content into another key `content`. So essentially, it becomes:
`{ path: './bodyPath.js', content: 'content fron bodyPath.js' }`
The `YAML.vistor` function does all the magic here. 
While traversing the nodes, we check if the current node is the `job body`. We know that it's the job body by moving up the `path tree` until we find a node with the key `jobs`. Here's how the path tree looks like:
```bash
[
Document {
....
contents: YAMLMap { items: [Array], range: [Array] },
range: [ 0, 972, 972 ]
},
YAMLMap { items: [ [Pair], [Pair] ], range: [ 0, 972, 972 ] },
Pair {
key: Scalar {
value: 'workflows',
...
},
value: YAMLMap { items: [Array], range: [Array] }
},
YAMLMap { items: [ [Pair] ], …
```
> Support file path in job body

- .changeset/grumpy-knives-drop.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/lightning-mock/src/api-sockets.ts
- packages/lightning-mock/src/server.ts
- packages/lightning-mock/src/socket-server.ts
- packages/lightning-mock/test/socket-server.test.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/api/destroy.ts
- packages/ws-worker/src/channels/worker-queue.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/util/cli.ts
- packages/ws-worker/test/channels/worker-queue.test.ts
- packages/ws-worker/test/lightning.test.ts
Adds WORKER_MAX_SOCKET_TIMEOUT_SECONDS variable to  control socket timeouts.
A few other tiny logging tweaks here.
> Worker: Log improvements and WORKER_MAX_SOCKET_TIMEOUT_SECONDS

- .changeset/curvy-onions-tease.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- integration-tests/worker/test/exit-reasons.test.ts
- packages/lightning-mock/src/start.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/destroy.ts
- packages/ws-worker/src/api/execute.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/util/create-run-state.ts
- packages/ws-worker/test/util/create-run-state.test.ts
We're seeing an error where the worker will blow up if a run does not have a start node (or specifies a start node which does not exist).
This causes the worker to immediately exit and all outstanding runs will be lost. Not a great look.
Fixes #758 
The fix is easy enough and I've added unit tests. The runtime will catch the inconsistent workflow structure and raise an exception for us - we just need the worker to not blow up before this happens.
There are a few other areas around this code where an exception will blow up the worker. I've raised an issue to track them #759  but I don't think I want to take them on here. Let's just fix the immediate issue.
> Worker: don't blow up if a run doesn't have a start node

- .changeset/late-eels-relax.md
- examples/dts-inspector/CHANGELOG.md
- examples/dts-inspector/package.json
- integration-tests/execute/CHANGELOG.md
- integration-tests/execute/package.json
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/describe-package/CHANGELOG.md
- packages/describe-package/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- pnpm-lock.yaml
Update dev dependencies to use a version to `@openfn/language-common` that does not depend on a vulnerable version of axios.
Fixes #768 
A more detailed breakdown of the changes, including motivations (if not provided in the issue).
> Use language-common that does not depend on axios

- .changeset/plenty-cobras-join.md
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
Include run durations in logging
> Better worker logs

- .github/pull_request_template.md
> github: update pull request template with AI stuff

- .changeset/red-flies-mix.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/lightning-mock/src/server.ts
- packages/lightning-mock/src/start.ts
- packages/lightning-mock/src/tokens.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/api/destroy.ts
- packages/ws-worker/src/api/workloop.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/test/api/workloop.test.ts
- packages/ws-worker/test/lightning.test.ts
When the worker is at capacity, it will now terminate the workloop and stop trying to claim.
Once the server is back to capacity, it'll resume the workloop, resetting the backoff to the initial value.
Logging has also been improved.
I've tested this manually - I'm trying to think of a decent automated test. It is a little hard to quanty the backoffs..
#786
> Worker: better handling of backoff when at capacity

- .changeset/healthy-kangaroos-cross.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/engine-multi/src/api/lifecycle.ts
- packages/engine-multi/src/events.ts
- packages/engine-multi/test/api/lifecycle.test.ts
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
Includes timestamp on `JOB_ERROR` event payload
Fixes #794 
> engine: Include timestamp on `JOB_ERROR`

- .changeset/shiny-fans-tickle.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/deploy/CHANGELOG.md
- packages/deploy/package.json
- packages/deploy/src/stateTransform.ts
- packages/deploy/src/types.ts
- packages/deploy/test/stateTransform.test.ts
This pull request adds `kafka` trigger type. 
Fixes #796 
- The structure maintains the structure as it is in lightning
- There is a validation that uses regex to ensure that the host is in the form `hostname:number`
> CLI: Support kafka trigger type

- .changeset/spicy-parents-guess.md
- packages/cli/src/compile/compile.ts
- packages/compiler/src/util.ts
- packages/engine-multi/src/api/compile.ts
There's a very gnarly bit of compiler code called `preloadAdaptorExports` which tries to work out the list of valid exports from an adaptor.
We've had a lot of trouble around this historically - it doesn't actually work terrible well, and relies on some ropey, poorly tested code in `describe-adaptor`
The problem right now is that the list of exports for an adaptor is very generous. We basically list every export listed in the d.ts (regardless of how or where it's exported). And for some reason we also list everything exported from common, regardless of whether it's actually exported from the adaptor. Frankly I forget what this is all about.
Now this is a problem when we have multiple adaptors, a la collections, because the compiler things that both `http` and collections export `fn`, so …
> compiler: don't extract common exports

- .changeset/eleven-cougars-exist.md
- .changeset/healthy-laws-sniff.md
- .changeset/loud-crabs-walk.md
- packages/lexicon/core.d.ts
- packages/runtime/src/execute/compile-plan.ts
- packages/runtime/src/execute/step.ts
- packages/runtime/src/types.ts
- packages/runtime/src/util/assemble-state.ts
- packages/runtime/test/execute/compile-plan.test.ts
- packages/runtime/test/runtime.test.ts
- packages/runtime/test/util/assemble-state.test.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/util/convert-lightning-plan.ts
- packages/ws-worker/test/lightning.test.ts
- packages/ws-worker/test/util/convert-lightning-plan.test.ts
This PR adds the capability for what I'm calling "global credentials" in the runtime.
What that means is you can specify a credential on root of the workflow JSON, and it'll automatically be grafted into every step in state.configuration.
This feels like a logical and intuitive feature - but it's also a great use-case for collections. It provides a really neat mechanism for the worker to add system-level credentials.
I mean the alternative is to support `credentials` as an array, which is sort of covered in #802. But this is  gnarly change and too big for what I was looking for with collections.
Fixes #
If we detect possible use of the collections API in job code (literally just the string `collections.`), the worker create a global credential on the execution plan, adding …
> Global credentials

- .changeset/stale-taxis-attack.md
- integration-tests/worker/src/init.ts
- integration-tests/worker/test/server.test.ts
- packages/ws-worker/src/channels/run.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/util/cli.ts
- packages/ws-worker/src/util/convert-lightning-plan.ts
- packages/ws-worker/test/channels/run.test.ts
- packages/ws-worker/test/util/convert-lightning-plan.test.ts
This PR levelsup the worker to know about which version of the collections adaptor to be used.
You can pass in a version explicitly, via the cli or env var. If no version is provided, the server will look up the latest version on npm.
This arises because of #462, where in the worker needs to know a specific adaptor version to autoinstall (using latest all the time just doesn't work very well).
> Worker: set or lookup the collections adaptor version

- .changeset/curly-lions-prove.md
- integration-tests/execute/CHANGELOG.md
- integration-tests/execute/package.json
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/util/assemble-state.ts
- packages/runtime/test/util/assemble-state.test.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
This PR fixes a critical new issue, introduced by the collections work, where the initial state from a job gets blatted wrongly.
This affects CLI 1.8.6 and the (unreleased) worker 1.8.0
> Runtime: Fix input state assembly

- .changeset/chatty-clocks-relax.md
- packages/ws-worker/src/util/convert-lightning-plan.ts
- packages/ws-worker/test/util/convert-lightning-plan.test.ts
Little PR to allow a workflow step to provide its own collections version.
This isn't very useful really because Lightning would have to explicitly pass two adaptors into the attempt, which is a reasonably big change I would say.
Still, this was on my mind and I figure it's worth doing. It's not a big deal to the worker.
> worker: allow steps to specify their own adaptor version

- .changeset/big-paws-tap.md
- packages/ws-worker/src/server.ts
If you specify the collections versions number (as I do in local testing), everything works fine.
But if the worker looks up the latest collections version from npm, everything breaks!
This is because:
a) I am saving the adaptor version to the wrong place so it doesn't get used (whoops) 
b) the version number includes whitespace, which breaks the autoinstall command.
> Collections fix version lookup

- .changeset/angry-spoons-tie.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cli/src/deploy/handler.ts
- packages/cli/test/deploy/options.test.ts
Fixes an issue where the -p (project path) flag in the deploy command would default to `project.yaml` instead of using the specified file.
Fixes #286 
- Verify that running openfn deploy -p test1.yaml now correctly uses test1.yaml as the project file, without defaulting to project.yaml.
- Test other commands to ensure no unintended impact on flag handling.
- Check for cases where project.yaml should still be used as a default if the -p flag is omitted.
> Fix Project Path Flag Issue

- .changeset/sweet-bugs-breathe.md
- examples/dts-inspector/CHANGELOG.md
- examples/dts-inspector/package.json
- integration-tests/execute/CHANGELOG.md
- integration-tests/execute/package.json
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/describe-package/CHANGELOG.md
- packages/describe-package/package.json
- packages/describe-package/src/describe-project.ts
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
If an example includes a `{@link }` tag (and it shouldn't!), it'll trigger an error and docs won't show up in Lightning.
This fix makes the example parser more stable - but note that any offending examples will not be displayed in lightning's adaptor docs.
Fixes https://github.com/OpenFn/adaptors/issues/854
> describe-package: fix examples

- integration-tests/execute/CHANGELOG.md
- integration-tests/execute/ava.config.js
- integration-tests/execute/package.json
- integration-tests/execute/test/lazy-state.test.ts
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/compiler/src/transforms/lazy-state.ts
- packages/compiler/test/transforms/lazy-state.test.ts
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
Currently function calls on lazy-state do not work. 
eg. 
```js
fn((state) => {
state.callMeMaybe = () => {}
return state
});
// does not work before this PR
fn($.callMeMaybe())
```
This is because, we fail to wrap the state callback well. This update fixes that.
Given the source code `fn($.callMeMaybe())`
| Before this PR                             | After this PR                            |
|--------------------------------------------|------------------------------------------|
| ``` fn((state => state.callMeMaybe)()) ``` | ``` fn(state => state.callMeMaybe()) ``` |
Fixes #684 
1. after finding the MemberExpression with $, we start walking up the tree to find a CallExpression to wrap. 
2. when we find this CallExpression, a simple check is done to find out whether the parent of this …
> Compiler: allow function calls on lazy state

- .changeset/hungry-windows-search.md
- integration-tests/cli/test/errors.test.ts
- integration-tests/cli/test/fixtures/errors.json
- packages/cli/src/compile/compile.ts
- packages/compiler/package.json
- packages/compiler/src/compile.ts
- packages/compiler/src/parse.ts
- packages/compiler/src/transform.ts
- packages/compiler/src/transforms/top-level-operations.ts
- packages/compiler/test/compile.test.ts
- packages/compiler/test/transforms/top-level-operations.test.ts
- packages/lexicon/core.d.ts
- packages/runtime/src/errors.ts
- packages/runtime/src/execute/context.ts
- packages/runtime/src/execute/expression.ts
- packages/runtime/src/execute/plan.ts
- packages/runtime/src/execute/step.ts
- packages/runtime/src/runtime.ts
- packages/runtime/src/types.ts
- packages/runtime/src/util/log-error.ts
- packages/runtime/test/__modules__/test/index.js
- packages/runtime/test/errors.test.ts
- packages/runtime/test/execute/wrap-operation.test.ts
- pnpm-lock.yaml
Hit a bit of a problem in source mapping.
The whole idea was to map against the error position in the original source, based mostly on finding errors which come out of the vm and simply mapping the position back.
But errors which occur from adaptor code - from top level operations -  don't actually have vm code in the stack. The operation is initialised in the vm, but the actual runtime callstack only has runtime call code.
The problem is that in the source code, we just call operations at the top level and they look like function calls. But actually they're compiled into an array and exported from the "module" and executed in series. The code that's actually executed is really not part of the VM.
This makes it super hard to map back to the VM.
This PR does a couple of things to help …
> Sourcemapping adaptor errors

- .changeset/eleven-owls-decide.md
- integration-tests/execute/CHANGELOG.md
- integration-tests/execute/package.json
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/runtime/src/execute/expression.ts
- packages/runtime/test/execute/wrap-operation.test.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
When the vm throws an error, we try and determine if that error comes from an adaptor. This makes assumptions about the callstack and the path of the file. It works fine for production adaptors, but when loading from the monorepo these tests fail.
Fixes #855 
I am reproducing like this:
* In the monorepo, add this to common:
```
```
* Create a simple job which just calls `tmp()`
* From `packages/cli`, run `pnpm openfn tmp/job.js -ma common` (where tmp/job.js points to the simple job)
* Against production, the error contains no details. Here, you get output like:
```
[CLI] ♦ Versions:
▸ node.js                    22.12.0
▸ cli                        1.10.0
▸ @openfn/language-common    monorepo
[CLI] ✔ Loading adaptors from monorepo at /home/joe/repo/openfn/adaptors
[CLI] ⚠ Skipping …
```
> Fix errors when using the monorepo

- integration-tests/cli/test/autoinstall.test.ts
- integration-tests/cli/test/execute-workflow.test.ts
- integration-tests/cli/test/fixtures/different-adaptor-versions.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/cli/src/execute/handler.ts
- packages/cli/src/util/override-plan-adaptors.ts
- packages/cli/test/util/override-plan-adaptor.test.ts
When alias adaptor versions are used in cli, the runtime is unable to resolve them. resulting in the error below
This is because, During the installation step, `@latest` is resolved to the latest version but then during execution, we try linking `@latest` instead of the resolved version.
Fixes #853 
Replacing adaptors in a plan with already resolved adaptors before the plan gets passed to the compiler and the runtime.
<table><thead>
<tr>
<th>Workflow</th>
<th>Logs</th>
</tr></thead>
<tbody>
<tr>
<td><img width="558" alt="Screenshot 2025-01-14 at 11 55 13 AM" src="https://github.com/user-attachments/assets/0936d412-9722-4b7a-b727-08d0c124ed2b" /></td>
<td><img width="558" alt="Screenshot 2025-01-14 at 11 55 13 AM" src="https://github.com/user-attachments/assets/cb3971ff-29fa-4a6a-b78c-22318 …
> fix: replace adaptors in plan with resolved adaptors at install

- .changeset/green-countries-reflect.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/deploy/CHANGELOG.md
- packages/deploy/package.json
- packages/deploy/src/stateTransform.ts
- packages/deploy/src/types.ts
- packages/deploy/src/validator.ts
- packages/deploy/test/fixtures.ts
- packages/deploy/test/stateTransform.test.ts
- pnpm-lock.yaml
Add support for collections in cli deploy package via the `collections` key.
You can `add, update and delete` collections. 
Fixes #858
Can be tested using https://github.com/OpenFn/lightning/pull/2852
> CLI Deploy: support collections

- .changeset/shiny-swans-care.md
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/deploy/CHANGELOG.md
- packages/deploy/package.json
- packages/deploy/src/stateTransform.ts
- packages/deploy/src/types.ts
- packages/deploy/test/stateTransform.test.ts
This PR makes the `collections` key optional in the `ProjectPayload`. When the `ProjectState` has an empty collections key, `[]`, the key gets dropped from the payload.
Fixes #861
> CLI Deploy: Don't send empty collections

- .circleci/config.yml
- README.md
Corepack has updated npm registry keys and some older versions have expired.
This PR forces a bump of the corepack version
See https://github.com/nodejs/corepack/issues/612
And see https://github.com/nodejs/corepack/issues/616
> Fix CircleCI install

- .changeset/unlucky-panthers-try.md
- integration-tests/execute/CHANGELOG.md
- integration-tests/execute/package.json
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- integration-tests/worker/test/integration.test.ts
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/engine-multi/src/worker/thread/helpers.ts
- packages/engine-multi/src/worker/thread/run.ts
- packages/lexicon/CHANGELOG.md
- packages/lexicon/lightning.d.ts
- packages/lexicon/package.json
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/util/convert-lightning-plan.ts
- pnpm-lock.yaml
This PR adds support for `job_log_level` in lightning plan. This is eventually passed down to the engine
Fixes #868 
> ws-worker: support job log level in lightning plan

- .changeset/fair-deers-marry.md
- packages/runtime/src/execute/step.ts
Removes wrong formatting of run complete duration.
Fixes #875 
Easy fix.
Do you see msms anymore on run complete logs?
> fix: wrong formatting of run complete time

- .changeset/beige-kings-speak.md
- integration-tests/worker/src/init.ts
- integration-tests/worker/test/integration.test.ts
- packages/engine-multi/src/api/execute.ts
- packages/engine-multi/src/engine.ts
- packages/engine-multi/src/types.ts
- packages/engine-multi/test/api/execute.test.ts
This PR fixes an issue with the new `jobLogLevel` option sent from Lightning, which it turns out isn't working ¯\\_(ツ)_/¯
Two problems:
1) The `jobLogLevel` option wasn't getting properly fed through to the engine's options
2) The integration test was accidentally passing because it checked the logger's stdout to see  if the job log was present. But the engine actually doesn't send job logs to stdout, it just forwards them straight to the worker. Confusing!
https://github.com/OpenFn/kit/blob/10ad46888bec8a4333de6481940f54907f8ceac1/packages/engine-multi/src/api/lifecycle.ts#L127-L150
So to fix the test, we instead listen to the log events that Lightning receives. Which is a better test anyway because taht's actually the thing we care about.
Please disclose how you've used AI in this work …
> Fix worker log level

- .changeset/forty-avocados-boil.md
- integration-tests/worker/CHANGELOG.md
- integration-tests/worker/package.json
- packages/engine-multi/CHANGELOG.md
- packages/engine-multi/package.json
- packages/engine-multi/src/api/preload-credentials.ts
- packages/lightning-mock/CHANGELOG.md
- packages/lightning-mock/package.json
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
Quick maintenance update to help with #898
> Better credential error logging

- .changeset/eight-parents-add.md
- .changeset/old-swans-clean.md
- integration-tests/worker/test/integration.test.ts
- packages/logger/src/logger.ts
- packages/logger/test/logger.test.ts
In the logger, when running in json mode (ie, emit JSON objects, not strings), ignore anything with an empty message.
Fixes #899
This PR is a little misleading because _really_ what it does is prevents the worker sending empty log lines to Lightning.
But the implementation can be handled very neatly by the low level logging component. It'll simply not emit any empty log lines.
This makes sense: json logging is designed for tools to consume logs. And those tools don't need formatting log lines. Usually in the runtime we print empty lines to make the CLI pretty.
Note that `console.log(undefined)` will still log.
You can read more details in our [Responsible AI …
> Logger: ignore empty lines in JSON Mode

- .changeset/tough-buttons-vanish.md
- packages/lexicon/lightning.d.ts
- packages/ws-worker/src/api/claim.ts
On claim report the pod name from the environment. This is harmless if no env var is set.
The logs look like this:
```
[SRV] ❯ [Joe's cool pod] claimed 1 runs in 8ms (2fa0a8e0-12b0-4d6e-9e5d-f1720a4f2a7e)
[SRV] ❯ verified run token for 2fa0a8e0-12b0-4d6e-9e5d-f1720a4f2a7e
[SRV] ❯ [Joe's cool pod]  starting run 2fa0a8e0-12b0-4d6e-9e5d-f1720a4f2a7e
```
> Report podname

- .changeset/late-snakes-happen.md
- .changeset/weak-teachers-give.md
- integration-tests/worker/src/init.ts
- integration-tests/worker/test/server.test.ts
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/api/workloop.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/util/cli.ts
- packages/ws-worker/src/util/try-with-backoff.ts
- packages/ws-worker/test/lightning.test.ts
The actual fix is dead simple: when we call `resumeWorkloop`, don't actually resume if the server is marked as destroyed.
The difficulty is getting the integration test to pass. There's a strange issue where the mock doesn't emit claim events while there's a run in progress, which is blocking the tests.
I might be able to create better tests against the worker directly. Or we'll leave the fix on faith and merge it.
Closes #946 
> Fix claim after sigterm

- .changeset/mean-poets-sip.md
- packages/ws-worker/src/channels/worker-queue.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/src/start.ts
- packages/ws-worker/src/util/cli.ts
- packages/ws-worker/test/channels/worker-queue.test.ts
The point between a Worker _claiming_ a Run and _starting_ it is super delicate.
Right now, if the claim event takes too long, it'll timeout. The run will be removed from the queue but won't get started by the worker.
This PR forces the timeout on claim to be super long to give it the maximum chance to download the run id to the worker.
It's a crude solution but it feels necessary at this point.
Closes #981 (at least for now)
> Worker: force a super long timeout on claims

- .changeset/tender-parrots-agree.md
- packages/cli/src/compile/command.ts
- packages/cli/src/compile/compile.ts
- packages/cli/src/execute/command.ts
- packages/cli/src/options.ts
- packages/compiler/src/compile.ts
- packages/compiler/src/parse.ts
- packages/compiler/src/transform.ts
- packages/compiler/src/transforms/add-imports.ts
- packages/compiler/src/transforms/ensure-exports.ts
- packages/compiler/src/transforms/lazy-state.ts
- packages/compiler/src/transforms/top-level-operations.ts
- packages/compiler/src/util.ts
This PR reduces the memory overhead of compilation by making some visitors exit early
I'm parsing 1.6mb Javascript file here which, in production takes around 350mb to parse.
This PR brings that down to around 270mb.
Note that I've added a little `trace` option to the compiler, although I haven't added it to the CLI yet. Should really add it as an undocumented option.
This is just a quick win really. I think we need to figure out how to do #1011 properly, which will take some thinking (I sure hope our unit tests are good enough to catch regressions, that'll be a risky job)
Closes #744
> Reduce compiler memory overhead

- .changeset/wild-trees-wink.md
- packages/cli/src/options.ts
- packages/cli/src/util/validate-plan.ts
The issue is that
1. Our step validation code doesn't allow `type` as a key.
2. We weren't getting the base directory well when the path passed to the command line was a `.yaml` or `.yml` file. we were considering just `.json` well.
A more detailed breakdown of the changes, including motivations (if not provided in the issue).
> fix: yaml execution error

- .changeset/cuddly-apples-buy.md
- packages/lightning-mock/src/server.ts
- packages/lightning-mock/src/types.ts
- packages/ws-worker/CHANGELOG.md
- packages/ws-worker/package.json
- packages/ws-worker/src/api/claim.ts
- packages/ws-worker/src/api/destroy.ts
- packages/ws-worker/src/events.ts
- packages/ws-worker/src/server.ts
- packages/ws-worker/test/api/claim.test.ts
- packages/ws-worker/test/api/destroy.test.ts
- packages/ws-worker/test/api/workloop.test.ts
No issue: I learned this afternoon that some lost runs are caused by the worker receiving a SIGTERM while claims are still outstanding.
If lightning happens to have released these claims, the worker will shut down and renege on its promise to complete the work.
As a result of this PR, the worker will now wait for all outstanding claims, and their associated runs, before shutting down.
Most of the effort was in getting the test to work - took a bunch of refactoring :sweat_smile: 
> worker: don't destroy until all outstanding claims have come home
